/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum DIRECT3D11 {
    D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS = 0x887C0001,
    D3D11_ERROR_FILE_NOT_FOUND = 0x887C0002,
    D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS = 0x887C0003,
    D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD = 0x887C0004,
    AEERR_ALREADY_INITIALIZED = 0x887C0010,
    AEERR_NOT_INITIALIZED = 0x887C0013,
    AEERR_MISALIGNED_BUFFER = 0x887C0014,
    AEERR_NO_REALTIME = 0x887C0015,
    AEERR_ALREADY_RUNNING = 0x887C0016,
    AEERR_NOT_RUNNING = 0x887C0017,
    AEERR_APO_NOT_READY = 0x887C0018,
    AEERR_ITEM_NOT_FOUND = 0x887C001A,
    AEERR_MAX_CONNECTIONS_SET = 0x887C001B,
    AEERR_MIN_CONNECTIONS_SET = 0x887C001C,
    AEERR_OBJECT_BUSY = 0x887C001D,
    AEERR_INVALID_CONNECTION_FORMAT = 0x887C001E,
    AEERR_INPLACE_NOTALLOWED = 0x887C001F,
    AEERR_INVALID_MIX_FLAGS = 0x887C0020,
    AEERR_TIME_IS_PAST = 0x887C0022,
    AEERR_BUFFER_NOT_LOCKED = 0x887C0023,
    AEERR_DATA_POINTER_NOT_RELEASED = 0x887C0024,
    AEERR_DATA_POINTER_NOT_ACQUIRED = 0x887C0025,
    AEERR_CONNECTION_ATTACHED_TO_APO = 0x887C0027,
    AEERR_ENDPOINT_ALREADY_ATTACHED = 0x887C0028,
    AEERR_PIPE_NOT_CONNECTABLE = 0x887C0029,
    AEERR_PIPE_LIMIT_REACHED = 0x887C002A,
    AEERR_ADG_NO_PIPE_INSTANCES = 0x887C002B,
    AEERR_ADG_ALREADY_CONNECTED = 0x887C002E,
    AEERR_TRANSACTION_ALREADY_IN_PROGRESS = 0x887C002F,
    AEERR_NO_CONVERTERS_FOUND = 0x887C0030,
    AEERR_TRANSACTION_MUST_BE_CANCELLED = 0x887C0031,
    AEERR_TRANSACTION_MUST_BE_COMMITTED = 0x887C0032,
    AEERR_TIMED_OUT = 0x887C0033,
    AEERR_FORMAT_NOT_SUPPORTED = 0x887C0034,
    AEERR_ENDPOINT_STATE_NOT_VALID = 0x887C0035,
    AEERR_ENDPOINT_CREATE_FAILED = 0x887C0036,
    AEERR_ADG_APO_NOT_USABLE = 0x887C0037,
    AEERR_ADG_SAMPLE_RATE_MISMATCH = 0x887C0039,
    AEERR_APO_NOT_REGISTERED = 0x887C003A,
    AEERR_APO_REGISTRY = 0x887C003B,
    AEERR_ADG_INVALID_GRAPH = 0x887C003C,
    AEERR_INVALID_DITHER_STATE = 0x887C003D,
    AEERR_INVALID_TIMESTAMP = 0x887C003F,
    AEERR_ENDPOINT_IO = 0x887C0040,
    AEERR_CP_MUTEX_ABONDENED = 0x887C0041,
    AEERR_INVALID_FRAMERATE = 0x887C0042,
    AEERR_DEVICE_IN_USE = 0x887C0043,
    AEERR_PERFLIB_NOFUNC = 0x887C0044,
    AEERR_CP_SHARED_BUFFER_CORRUPT = 0x887C0045,
    AEERR_ADG_INVALID_PROCESSING_PERIOD = 0x887C0046,
    AEERR_CP_QUEUE_FULL = 0x887C0047,
    AEERR_APO_INVALIDARG = 0x887C0048,
    AEERR_NO_HEAP = 0x887C0049,
    AEERR_HEAP_ALREADY_CREATED = 0x887C004A,
    AEERR_ACTIVE_STREAM_COUNT_ERR = 0x887C004B,
    AEERR_ENDPOINT_IN_USE = 0x887C00AA,
}

impl DIRECT3D11 {
    pub fn description(&self) -> &'static str {
        match self {
            DIRECT3D11::D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS => "The application has exceeded the maximum number of unique state objects per Direct3D device.",
            DIRECT3D11::D3D11_ERROR_FILE_NOT_FOUND => "The specified file was not found.",
            DIRECT3D11::D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS => "The application has exceeded the maximum number of unique view objects per Direct3D device.",
            DIRECT3D11::D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD => "The application's first call per command list to Map on a deferred context did not use D3D11_MAP_WRITE_DISCARD.",
            DIRECT3D11::AEERR_ALREADY_INITIALIZED => "The object has already been initialized.",
            DIRECT3D11::AEERR_NOT_INITIALIZED => "Object/structure is not initialized.",
            DIRECT3D11::AEERR_MISALIGNED_BUFFER => "Misaligned buffer usage.",
            DIRECT3D11::AEERR_NO_REALTIME => "Failed to allocate a real-time thread.",
            DIRECT3D11::AEERR_ALREADY_RUNNING => "Already in a running state.",
            DIRECT3D11::AEERR_NOT_RUNNING => "Not in a running state.",
            DIRECT3D11::AEERR_APO_NOT_READY => "APO is not ready to process.",
            DIRECT3D11::AEERR_ITEM_NOT_FOUND => "Item not found in list.",
            DIRECT3D11::AEERR_MAX_CONNECTIONS_SET => "Maximum number of input or output connections already set on this APO.",
            DIRECT3D11::AEERR_MIN_CONNECTIONS_SET => "Minimum number of input or output connections are set on this APO.",
            DIRECT3D11::AEERR_OBJECT_BUSY => "Object is busy performing some operation.",
            DIRECT3D11::AEERR_INVALID_CONNECTION_FORMAT => "Invalid connection format for this operation.",
            DIRECT3D11::AEERR_INPLACE_NOTALLOWED => "Inplace not allowed on this APO.",
            DIRECT3D11::AEERR_INVALID_MIX_FLAGS => "Invalid mix flags.",
            DIRECT3D11::AEERR_TIME_IS_PAST => "Invalid timestamp (time has already gone by).",
            DIRECT3D11::AEERR_BUFFER_NOT_LOCKED => "Invalid data pointer (the pointer has not been locked).",
            DIRECT3D11::AEERR_DATA_POINTER_NOT_RELEASED => "Data pointer not released (GetDataPointer was called twice).",
            DIRECT3D11::AEERR_DATA_POINTER_NOT_ACQUIRED => "Data pointer not acquired (Release was called without get).",
            DIRECT3D11::AEERR_CONNECTION_ATTACHED_TO_APO => "Connection is attached to an apo and cannot be released.",
            DIRECT3D11::AEERR_ENDPOINT_ALREADY_ATTACHED => "Connection already attached to an endpoint.",
            DIRECT3D11::AEERR_PIPE_NOT_CONNECTABLE => "The pipe contains APOs that cannot be connected.",
            DIRECT3D11::AEERR_PIPE_LIMIT_REACHED => "The pipe contains APOs that cannot be connected.",
            DIRECT3D11::AEERR_ADG_NO_PIPE_INSTANCES => "The audiodevicegraph does not have any pipe instances.",
            DIRECT3D11::AEERR_ADG_ALREADY_CONNECTED => "The audiodevicegraph is already connected.",
            DIRECT3D11::AEERR_TRANSACTION_ALREADY_IN_PROGRESS => "There is already a transaction in progress.",
            DIRECT3D11::AEERR_NO_CONVERTERS_FOUND => "No format converters were found.",
            DIRECT3D11::AEERR_TRANSACTION_MUST_BE_CANCELLED => "The transaction must be cancelled (because it was already attempted but failed to cancel).",
            DIRECT3D11::AEERR_TRANSACTION_MUST_BE_COMMITTED => "The transaction must be committed (because it was already attempted but failed to commit).",
            DIRECT3D11::AEERR_TIMED_OUT => "Time out occurred.",
            DIRECT3D11::AEERR_FORMAT_NOT_SUPPORTED => "A pin supporting the format cannot be found.",
            DIRECT3D11::AEERR_ENDPOINT_STATE_NOT_VALID => "Endpoint state is invalid for the required operation.",
            DIRECT3D11::AEERR_ENDPOINT_CREATE_FAILED => "Endpoint creation failed.",
            DIRECT3D11::AEERR_ADG_APO_NOT_USABLE => "An APO is not usable for ADG. See AUDIO_PIPE_DESCRIPTOR for details.",
            DIRECT3D11::AEERR_ADG_SAMPLE_RATE_MISMATCH => "ADG does not support SRC within a pipe.",
            DIRECT3D11::AEERR_APO_NOT_REGISTERED => "APO is not registered.",
            DIRECT3D11::AEERR_APO_REGISTRY => "An unexpected error occurred when reading APO properties.",
            DIRECT3D11::AEERR_ADG_INVALID_GRAPH => "An unexpected error occurred in audio device graph.",
            DIRECT3D11::AEERR_INVALID_DITHER_STATE => "Invalid dither state.",
            DIRECT3D11::AEERR_INVALID_TIMESTAMP => "The time-stamp is invalid.",
            DIRECT3D11::AEERR_ENDPOINT_IO => "The endpoint failed IO with the driver.",
            DIRECT3D11::AEERR_CP_MUTEX_ABONDENED => "The crossprocess synchronization mutex was abandoned.",
            DIRECT3D11::AEERR_INVALID_FRAMERATE => "Frame rates differ from initialization rates.",
            DIRECT3D11::AEERR_DEVICE_IN_USE => "The device is already in use.",
            DIRECT3D11::AEERR_PERFLIB_NOFUNC => "No supported function available in Audio PerfLib.",
            DIRECT3D11::AEERR_CP_SHARED_BUFFER_CORRUPT => "The crossprocess shared buffer is corrupted.",
            DIRECT3D11::AEERR_ADG_INVALID_PROCESSING_PERIOD => "Invalid ADG global graph processing period.",
            DIRECT3D11::AEERR_CP_QUEUE_FULL => "The crossprocess capture queue is full.",
            DIRECT3D11::AEERR_APO_INVALIDARG => "Invalid APO parameter.",
            DIRECT3D11::AEERR_NO_HEAP => "AudioProcessor heap is not created.",
            DIRECT3D11::AEERR_HEAP_ALREADY_CREATED => "AudioProcessor heap is already created.",
            DIRECT3D11::AEERR_ACTIVE_STREAM_COUNT_ERR => "AudioProcessor wrong active stream count.",
            DIRECT3D11::AEERR_ENDPOINT_IN_USE => "PinInstantiate returned ERROR_NO_SYSTEM_RESOURCES.",
        }
    }
}
