/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum MCA {
    MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED = 0x40050070,
    MCA_INFO_NO_MORE_CORRECTED_ERROR_LOGS = 0x40050073,
    MCA_INFO_MEMORY_PAGE_MARKED_BAD = 0x40050074,
    AUDIT_CARD_WRITTEN = 0x40050200,
    AUDIT_CARD_DELETE = 0x40050201,
    AUDIT_CARD_IMPORT = 0x40050202,
    AUDIT_STORE_IMPORT = 0x40050203,
    AUDIT_STORE_EXPORT = 0x40050204,
    AUDIT_STORE_DELETE = 0x40050205,
    AUDIT_SERVICE_IDLE_STOP = 0x40050206,
    E_EVAL_EXPIRED = 0x80050010,
    LTMM_E_INVALID_DATA = 0x80050013,
    LTMM_E_INVALID_HEADER = 0x80050014,
    LTMM_E_DISABLED = 0x80050015,
    LTMM_E_INVALID_VERSION = 0x80050016,
    LTMM_E_STILLIMAGE_LOCKED = 0x80050017,
    MCA_WARNING_CACHE = 0x8005003C,
    MCA_WARNING_TLB = 0x8005003E,
    MCA_WARNING_CPU_BUS = 0x80050040,
    MCA_WARNING_REGISTER_FILE = 0x80050042,
    MCA_WARNING_MAS = 0x80050044,
    MCA_WARNING_MEM_UNKNOWN = 0x80050046,
    MCA_WARNING_MEM_1_2 = 0x80050048,
    MCA_WARNING_MEM_1_2_5 = 0x8005004A,
    MCA_WARNING_MEM_1_2_5_4 = 0x8005004C,
    MCA_WARNING_SYSTEM_EVENT = 0x8005004E,
    MCA_WARNING_PCI_BUS_PARITY = 0x80050050,
    MCA_WARNING_PCI_BUS_PARITY_NO_INFO = 0x80050052,
    MCA_WARNING_PCI_BUS_SERR = 0x80050054,
    MCA_WARNING_PCI_BUS_SERR_NO_INFO = 0x80050056,
    MCA_WARNING_PCI_BUS_MASTER_ABORT = 0x80050058,
    MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO = 0x8005005A,
    MCA_WARNING_PCI_BUS_TIMEOUT = 0x8005005C,
    MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO = 0x8005005E,
    MCA_WARNING_PCI_BUS_UNKNOWN = 0x80050060,
    MCA_WARNING_PCI_DEVICE = 0x80050062,
    MCA_WARNING_SMBIOS = 0x80050064,
    MCA_WARNING_PLATFORM_SPECIFIC = 0x80050066,
    MCA_WARNING_UNKNOWN = 0x80050068,
    MCA_WARNING_UNKNOWN_NO_CPU = 0x8005006A,
    MCA_WARNING_CMC_THRESHOLD_EXCEEDED = 0x8005006D,
    MCA_WARNING_CPE_THRESHOLD_EXCEEDED = 0x8005006E,
    MCA_WARNING_CPU_THERMAL_THROTTLED = 0x8005006F,
    MCA_WARNING_CPU = 0x80050071,
    MCA_ERROR_CACHE = 0xC005003D,
    MCA_ERROR_TLB = 0xC005003F,
    MCA_ERROR_CPU_BUS = 0xC0050041,
    MCA_ERROR_REGISTER_FILE = 0xC0050043,
    MCA_ERROR_MAS = 0xC0050045,
    MCA_ERROR_MEM_UNKNOWN = 0xC0050047,
    MCA_ERROR_MEM_1_2 = 0xC0050049,
    MCA_ERROR_MEM_1_2_5 = 0xC005004B,
    MCA_ERROR_MEM_1_2_5_4 = 0xC005004D,
    MCA_ERROR_SYSTEM_EVENT = 0xC005004F,
    MCA_ERROR_PCI_BUS_PARITY = 0xC0050051,
    MCA_ERROR_PCI_BUS_PARITY_NO_INFO = 0xC0050053,
    MCA_ERROR_PCI_BUS_SERR = 0xC0050055,
    MCA_ERROR_PCI_BUS_SERR_NO_INFO = 0xC0050057,
    MCA_ERROR_PCI_BUS_MASTER_ABORT = 0xC0050059,
    MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO = 0xC005005B,
    MCA_ERROR_PCI_BUS_TIMEOUT = 0xC005005D,
    MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO = 0xC005005F,
    MCA_ERROR_PCI_BUS_UNKNOWN = 0xC0050061,
    MCA_ERROR_PCI_DEVICE = 0xC0050063,
    MCA_ERROR_SMBIOS = 0xC0050065,
    MCA_ERROR_PLATFORM_SPECIFIC = 0xC0050067,
    MCA_ERROR_UNKNOWN = 0xC0050069,
    MCA_ERROR_UNKNOWN_NO_CPU = 0xC005006B,
    MCA_ERROR_CPU = 0xC0050072,
    MCA_MEMORYHIERARCHY_ERROR = 0xC0050078,
    MCA_TLB_ERROR = 0xC0050079,
    MCA_BUS_ERROR = 0xC005007A,
    MCA_BUS_TIMEOUT_ERROR = 0xC005007B,
    MCA_INTERNALTIMER_ERROR = 0xC005007C,
    MCA_MICROCODE_ROM_PARITY_ERROR = 0xC005007E,
    MCA_EXTERNAL_ERROR = 0xC005007F,
    MCA_FRC_ERROR = 0xC0050080,
    E_ICARD_COMMUNICATION = 0xC0050100,
    E_ICARD_DATA_ACCESS = 0xC0050101,
    E_ICARD_EXPORT = 0xC0050102,
    E_ICARD_IDENTITY = 0xC0050103,
    E_ICARD_IMPORT = 0xC0050104,
    E_ICARD_ARGUMENT = 0xC0050105,
    E_ICARD_REQUEST = 0xC0050106,
    E_ICARD_INFORMATIONCARD = 0xC0050107,
    E_ICARD_STOREKEY = 0xC0050108,
    E_ICARD_LOGOVALIDATION = 0xC0050109,
    E_ICARD_PASSWORDVALIDATION = 0xC005010A,
    E_ICARD_POLICY = 0xC005010B,
    E_ICARD_PROCESSDIED = 0xC005010C,
    E_ICARD_SERVICEBUSY = 0xC005010D,
    E_ICARD_SERVICE = 0xC005010E,
    E_ICARD_SHUTTINGDOWN = 0xC005010F,
    E_ICARD_TOKENCREATION = 0xC0050110,
    E_ICARD_TRUSTEXCHANGE = 0xC0050111,
    E_ICARD_UNTRUSTED = 0xC0050112,
    E_ICARD_USERCANCELLED = 0xC0050113,
    E_ICARD_STORE_IMPORT = 0xC0050114,
    E_ICARD_FAIL = 0xC0050115,
    E_ICARD_UI_INITIALIZATION = 0xC005011A,
    E_ICARD_REFRESH_REQUIRED = 0xC0050180,
    E_ICARD_MISSING_APPLIESTO = 0xC0050181,
    E_ICARD_INVALID_PROOF_KEY = 0xC0050182,
    E_ICARD_UNKNOWN_REFERENCE = 0xC0050183,
    E_ICARD_FAILED_REQUIRED_CLAIMS = 0xC0050184,
}

impl MCA {
    pub fn description(&self) -> &'static str {
        match self {
            MCA::MCA_INFO_CPU_THERMAL_THROTTLING_REMOVED => "Machine Check Event reported is a CPU thermal throttling event reported from CPU %1. The CPU has dropped below the temperature limit and throttling has been removed. %2 additional error(s) are contained within the record.",
            MCA::MCA_INFO_NO_MORE_CORRECTED_ERROR_LOGS => "The maximum number of Machine Check Event corrected error events that can be saved to the Event Log has been reached. Logging of these events has been disabled.",
            MCA::MCA_INFO_MEMORY_PAGE_MARKED_BAD => "The memory page at physical address %1 has encountered multiple corrected hardware error events. As a result it will no longer be used by Windows.",
            MCA::AUDIT_CARD_WRITTEN => "Description is missing",
            MCA::AUDIT_CARD_DELETE => "Description is missing",
            MCA::AUDIT_CARD_IMPORT => "Description is missing",
            MCA::AUDIT_STORE_IMPORT => "Description is missing",
            MCA::AUDIT_STORE_EXPORT => "Description is missing",
            MCA::AUDIT_STORE_DELETE => "Description is missing",
            MCA::AUDIT_SERVICE_IDLE_STOP => "Description is missing",
            MCA::E_EVAL_EXPIRED => "The evaluation period for the filter has expired.",
            MCA::LTMM_E_INVALID_DATA => "Invalid data.",
            MCA::LTMM_E_INVALID_HEADER => "Invalid packed data.",
            MCA::LTMM_E_DISABLED => "This feature is disabled.",
            MCA::LTMM_E_INVALID_VERSION => "This version is not supported.",
            MCA::LTMM_E_STILLIMAGE_LOCKED => "The LEADTOOLS still image toolkit needs to be unlocked.",
            MCA::MCA_WARNING_CACHE => "Machine Check Event reported is a corrected level %3 Cache error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_TLB => "Machine Check Event reported is a corrected level %3 translation Buffer error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_CPU_BUS => "Machine Check Event reported is a corrected External/Internal bus error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_REGISTER_FILE => "Machine Check Event reported is a corrected internal CPU register access error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_MAS => "Machine Check Event reported is a corrected Micro Architecture Structure error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_MEM_UNKNOWN => "Machine Check Event reported is a corrected ECC memory error at an unknown physical address reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_MEM_1_2 => "Machine Check Event reported is a corrected ECC memory error at physical address %3 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_MEM_1_2_5 => "Machine Check Event reported is a corrected ECC memory error at physical address %3 on memory module %4 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_MEM_1_2_5_4 => "Machine Check Event reported is a corrected ECC memory error at physical address %3 on memory module %4 on memory card %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_SYSTEM_EVENT => "Machine Check Event reported is a corrected System Event error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_PARITY => "Machine Check Event reported is a corrected PCI bus Parity error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_PARITY_NO_INFO => "Machine Check Event reported is a corrected PCI bus Parity error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_SERR => "Machine Check Event reported is a corrected PCI bus SERR error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_SERR_NO_INFO => "Machine Check Event reported is a corrected PCI bus SERR error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_MASTER_ABORT => "Machine Check Event reported is a corrected PCI bus Master abort error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_MASTER_ABORT_NO_INFO => "Machine Check Event reported is a corrected PCI bus Master abort error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_TIMEOUT => "Machine Check Event reported is a corrected PCI bus Timeout error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_TIMEOUT_NO_INFO => "Machine Check Event reported is a corrected PCI bus Timeout error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_BUS_UNKNOWN => "Machine Check Event reported is an unknown corrected PCI bus error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PCI_DEVICE => "Machine Check Event reported is a corrected PCI component error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_SMBIOS => "Machine Check Event reported is a corrected SMBIOS Device Type %3 error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_PLATFORM_SPECIFIC => "Machine Check Event reported is a corrected Platform Specific error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_UNKNOWN => "Machine Check Event reported is a corrected error reported to CPU %1.",
            MCA::MCA_WARNING_UNKNOWN_NO_CPU => "Machine Check Event reported is a corrected error.",
            MCA::MCA_WARNING_CMC_THRESHOLD_EXCEEDED => "Corrected Machine Check Interrupt threshold exceeded. Interrupt has been disabled. Polling mode has been enabled.",
            MCA::MCA_WARNING_CPE_THRESHOLD_EXCEEDED => "Corrected Platform Error Interrupt threshold exceeded. Interrupt has been disabled. Polling mode has been enabled.",
            MCA::MCA_WARNING_CPU_THERMAL_THROTTLED => "Machine Check Event reported is a CPU thermal throttling event reported from CPU %1. The CPU has exceeded the temperature limit and has been throttled down. %2 additional error(s) are contained within the record.",
            MCA::MCA_WARNING_CPU => "Machine Check Event reported is a corrected CPU error reported from CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_CACHE => "Machine Check Event reported is a fatal level %3 Cache error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_TLB => "Machine Check Event reported is a fatal level %3 translation Buffer error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_CPU_BUS => "Machine Check Event reported is a fatal External/Internal bus error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_REGISTER_FILE => "Machine Check Event reported is a fatal internal CPU register access error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_MAS => "Machine Check Event reported is a fatal Micro Architecture Structure error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_MEM_UNKNOWN => "Machine Check Event reported is a fatal ECC memory error at an unknown physical address reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_MEM_1_2 => "Machine Check Event reported is a fatal ECC memory error at physical address %3 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_MEM_1_2_5 => "Machine Check Event reported is a fatal ECC memory error at physical address %3 on memory module %4 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_MEM_1_2_5_4 => "Machine Check Event reported is a fatal ECC memory error at physical address %3 on memory module %4 on memory card %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_SYSTEM_EVENT => "Machine Check Event reported is a fatal System Event error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_PARITY => "Machine Check Event reported is a fatal PCI bus Parity error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_PARITY_NO_INFO => "Machine Check Event reported is a fatal PCI bus Parity error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_SERR => "Machine Check Event reported is a fatal PCI bus SERR error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_SERR_NO_INFO => "Machine Check Event reported is a fatal PCI bus SERR error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_MASTER_ABORT => "Machine Check Event reported is a fatal PCI bus Master abort error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_MASTER_ABORT_NO_INFO => "Machine Check Event reported is a fatal PCI bus Master abort error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_TIMEOUT => "Machine Check Event reported is a fatal PCI bus Timeout error during a transaction type %3 at address %4 on PCI bus %5 reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_TIMEOUT_NO_INFO => "Machine Check Event reported is a fatal PCI bus Timeout error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_BUS_UNKNOWN => "Machine Check Event reported is an unknown fatal PCI bus error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PCI_DEVICE => "Machine Check Event reported is a fatal PCI component error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_SMBIOS => "Machine Check Event reported is a fatal SMBIOS Device Type %3 error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_PLATFORM_SPECIFIC => "Machine Check Event reported is a fatal Platform Specific error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_ERROR_UNKNOWN => "Machine Check Event reported is a fatal error reported to CPU %1.",
            MCA::MCA_ERROR_UNKNOWN_NO_CPU => "Machine Check Event reported is a fatal error.",
            MCA::MCA_ERROR_CPU => "Machine Check Event reported is a fatal CPU error reported to CPU %1. %2 additional error(s) are contained within the record.",
            MCA::MCA_MEMORYHIERARCHY_ERROR => "Machine Check Event reported is a fatal memory hierarchy error.%r Trasaction Type: %1%r Memory Hierarchy Level: %2%r Request Type: %3%r Address: %4.",
            MCA::MCA_TLB_ERROR => "Machine Check Event reported is a fatal TLB error.%r Transaction Type: %1%r Memory Hierarchy Level: %2%r Address: %3.",
            MCA::MCA_BUS_ERROR => "Machine Check Event reported is a fatal Bus or Interconnect error.%r Memory Hierarchy Level: %1%r Participation: %2%r Request Type: %3%r Memory/IO: %4%r Address: %5.",
            MCA::MCA_BUS_TIMEOUT_ERROR => "Machine Check Event reported is a fatal Bus or Interconnect timeout error.%r Memory Hierarchy Level: %1%r Participation: %2%r Request Type: %3%r Memory/IO: %4%r Address: %5.",
            MCA::MCA_INTERNALTIMER_ERROR => "Machine Check Event reported is a fatal internal watchdog timer error.",
            MCA::MCA_MICROCODE_ROM_PARITY_ERROR => "Machine Check Event reported is a fatal microsoft ROM parity error.",
            MCA::MCA_EXTERNAL_ERROR => "Machine Check Event reported is a fatal condition. A processor received an external signal that an unrecoverable error has occurred.",
            MCA::MCA_FRC_ERROR => "Machine Check Event reported is a fatal functional redundancy check error.",
            MCA::E_ICARD_COMMUNICATION => "Description is missing",
            MCA::E_ICARD_DATA_ACCESS => "Description is missing",
            MCA::E_ICARD_EXPORT => "Description is missing",
            MCA::E_ICARD_IDENTITY => "Description is missing",
            MCA::E_ICARD_IMPORT => "Description is missing",
            MCA::E_ICARD_ARGUMENT => "Description is missing",
            MCA::E_ICARD_REQUEST => "Description is missing",
            MCA::E_ICARD_INFORMATIONCARD => "Description is missing",
            MCA::E_ICARD_STOREKEY => "Description is missing",
            MCA::E_ICARD_LOGOVALIDATION => "Description is missing",
            MCA::E_ICARD_PASSWORDVALIDATION => "Description is missing",
            MCA::E_ICARD_POLICY => "Description is missing",
            MCA::E_ICARD_PROCESSDIED => "Description is missing",
            MCA::E_ICARD_SERVICEBUSY => "Description is missing",
            MCA::E_ICARD_SERVICE => "Description is missing",
            MCA::E_ICARD_SHUTTINGDOWN => "Description is missing",
            MCA::E_ICARD_TOKENCREATION => "Description is missing",
            MCA::E_ICARD_TRUSTEXCHANGE => "Description is missing",
            MCA::E_ICARD_UNTRUSTED => "Description is missing",
            MCA::E_ICARD_USERCANCELLED => "Description is missing",
            MCA::E_ICARD_STORE_IMPORT => "Description is missing",
            MCA::E_ICARD_FAIL => "Description is missing",
            MCA::E_ICARD_UI_INITIALIZATION => "Description is missing",
            MCA::E_ICARD_REFRESH_REQUIRED => "Description is missing",
            MCA::E_ICARD_MISSING_APPLIESTO => "Description is missing",
            MCA::E_ICARD_INVALID_PROOF_KEY => "Description is missing",
            MCA::E_ICARD_UNKNOWN_REFERENCE => "Description is missing",
            MCA::E_ICARD_FAILED_REQUIRED_CLAIMS => "Description is missing",
        }
    }
}
