/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum P2P {
    PEER_S_GRAPH_DATA_CREATED = 0x00630001,
    PEER_S_NO_EVENT_DATA = 0x00630002,
    PEER_S_NO_CONNECTIVITY = 0x00630005,
    PEER_S_ALREADY_A_MEMBER = 0x00630006,
    PEER_S_ALREADY_CONNECTED = 0x00632000,
    PEER_S_SUBSCRIPTION_EXISTS = 0x00636000,
    PEER_E_IPV6_NOT_INSTALLED = 0x80630001,
    PEER_E_NOT_INITIALIZED = 0x80630002,
    PEER_E_CANNOT_START_SERVICE = 0x80630003,
    PEER_E_NOT_LICENSED = 0x80630004,
    PEER_E_INVALID_GRAPH = 0x80630010,
    PEER_E_DBNAME_CHANGED = 0x80630011,
    PEER_E_DUPLICATE_GRAPH = 0x80630012,
    PEER_E_GRAPH_NOT_READY = 0x80630013,
    PEER_E_GRAPH_SHUTTING_DOWN = 0x80630014,
    PEER_E_GRAPH_IN_USE = 0x80630015,
    PEER_E_INVALID_DATABASE = 0x80630016,
    PEER_E_TOO_MANY_ATTRIBUTES = 0x80630017,
    PEER_E_CONNECTION_NOT_FOUND = 0x80630103,
    PEER_E_CONNECT_SELF = 0x80630106,
    PEER_E_ALREADY_LISTENING = 0x80630107,
    PEER_E_NODE_NOT_FOUND = 0x80630108,
    PEER_E_CONNECTION_FAILED = 0x80630109,
    PEER_E_CONNECTION_NOT_AUTHENTICATED = 0x8063010A,
    PEER_E_CONNECTION_REFUSED = 0x8063010B,
    PEER_E_CLASSIFIER_TOO_LONG = 0x80630201,
    PEER_E_TOO_MANY_IDENTITIES = 0x80630202,
    PEER_E_NO_KEY_ACCESS = 0x80630203,
    PEER_E_GROUPS_EXIST = 0x80630204,
    PEER_E_RECORD_NOT_FOUND = 0x80630301,
    PEER_E_DATABASE_ACCESSDENIED = 0x80630302,
    PEER_E_DBINITIALIZATION_FAILED = 0x80630303,
    PEER_E_MAX_RECORD_SIZE_EXCEEDED = 0x80630304,
    PEER_E_DATABASE_ALREADY_PRESENT = 0x80630305,
    PEER_E_DATABASE_NOT_PRESENT = 0x80630306,
    PEER_E_IDENTITY_NOT_FOUND = 0x80630401,
    PEER_E_EVENT_HANDLE_NOT_FOUND = 0x80630501,
    PEER_E_INVALID_SEARCH = 0x80630601,
    PEER_E_INVALID_ATTRIBUTES = 0x80630602,
    PEER_E_INVITATION_NOT_TRUSTED = 0x80630701,
    PEER_E_CHAIN_TOO_LONG = 0x80630703,
    PEER_E_INVALID_TIME_PERIOD = 0x80630705,
    PEER_E_CIRCULAR_CHAIN_DETECTED = 0x80630706,
    PEER_E_CERT_STORE_CORRUPTED = 0x80630801,
    PEER_E_NO_CLOUD = 0x80631001,
    PEER_E_CLOUD_NAME_AMBIGUOUS = 0x80631005,
    PEER_E_INVALID_RECORD = 0x80632010,
    PEER_E_NOT_AUTHORIZED = 0x80632020,
    PEER_E_PASSWORD_DOES_NOT_MEET_POLICY = 0x80632021,
    PEER_E_DEFERRED_VALIDATION = 0x80632030,
    PEER_E_INVALID_GROUP_PROPERTIES = 0x80632040,
    PEER_E_INVALID_PEER_NAME = 0x80632050,
    PEER_E_INVALID_CLASSIFIER = 0x80632060,
    PEER_E_INVALID_FRIENDLY_NAME = 0x80632070,
    PEER_E_INVALID_ROLE_PROPERTY = 0x80632071,
    PEER_E_INVALID_CLASSIFIER_PROPERTY = 0x80632072,
    PEER_E_INVALID_RECORD_EXPIRATION = 0x80632080,
    PEER_E_INVALID_CREDENTIAL_INFO = 0x80632081,
    PEER_E_INVALID_CREDENTIAL = 0x80632082,
    PEER_E_INVALID_RECORD_SIZE = 0x80632083,
    PEER_E_UNSUPPORTED_VERSION = 0x80632090,
    PEER_E_GROUP_NOT_READY = 0x80632091,
    PEER_E_GROUP_IN_USE = 0x80632092,
    PEER_E_INVALID_GROUP = 0x80632093,
    PEER_E_NO_MEMBERS_FOUND = 0x80632094,
    PEER_E_NO_MEMBER_CONNECTIONS = 0x80632095,
    PEER_E_UNABLE_TO_LISTEN = 0x80632096,
    PEER_E_IDENTITY_DELETED = 0x806320A0,
    PEER_E_SERVICE_NOT_AVAILABLE = 0x806320A1,
    PEER_E_CANNOT_CONVERT_PEER_NAME = 0x80634001,
    PEER_E_INVALID_PEER_HOST_NAME = 0x80634002,
    PEER_E_NO_MORE = 0x80634003,
    PEER_E_PNRP_DUPLICATE_PEER_NAME = 0x80634005,
    PEER_E_CONTACT_NOT_FOUND = 0x80636001,
    PEER_E_INVITE_CANCELLED = 0x80637000,
    PEER_E_INVITE_RESPONSE_NOT_AVAILABLE = 0x80637001,
    PEER_E_NOT_SIGNED_IN = 0x80637003,
    PEER_E_PRIVACY_DECLINED = 0x80637004,
    PEER_E_TIMEOUT = 0x80637005,
    PEER_E_INVALID_ADDRESS = 0x80637007,
    PEER_E_FW_EXCEPTION_DISABLED = 0x80637008,
    PEER_E_FW_BLOCKED_BY_POLICY = 0x80637009,
    PEER_E_FW_BLOCKED_BY_SHIELDS_UP = 0x8063700A,
    PEER_E_FW_DECLINED = 0x8063700B,
}

impl P2P {
    pub fn description(&self) -> &'static str {
        match self {
            P2P::PEER_S_GRAPH_DATA_CREATED => "The graph data was created.",
            P2P::PEER_S_NO_EVENT_DATA => "There is not more event data.",
            P2P::PEER_S_NO_CONNECTIVITY => "No connectivity.",
            P2P::PEER_S_ALREADY_A_MEMBER => "Already a member.",
            P2P::PEER_S_ALREADY_CONNECTED => "The graph is already connect.",
            P2P::PEER_S_SUBSCRIPTION_EXISTS => "The subscription already exists.",
            P2P::PEER_E_IPV6_NOT_INSTALLED => "The IPv6 protocol is not installed.",
            P2P::PEER_E_NOT_INITIALIZED => "The component has not been initialized.",
            P2P::PEER_E_CANNOT_START_SERVICE => "The required service cannot be started.",
            P2P::PEER_E_NOT_LICENSED => "The P2P protocol is not licensed to run on this OS.",
            P2P::PEER_E_INVALID_GRAPH => "The graph handle is invalid.",
            P2P::PEER_E_DBNAME_CHANGED => "The graph database name has changed.",
            P2P::PEER_E_DUPLICATE_GRAPH => "A graph with the same ID already exists.",
            P2P::PEER_E_GRAPH_NOT_READY => "The graph is not ready.",
            P2P::PEER_E_GRAPH_SHUTTING_DOWN => "The graph is shutting down.",
            P2P::PEER_E_GRAPH_IN_USE => "The graph is still in use.",
            P2P::PEER_E_INVALID_DATABASE => "The graph database is corrupt.",
            P2P::PEER_E_TOO_MANY_ATTRIBUTES => "Too many attributes have been used.",
            P2P::PEER_E_CONNECTION_NOT_FOUND => "The connection can not be found.",
            P2P::PEER_E_CONNECT_SELF => "The peer attempted to connect to itself.",
            P2P::PEER_E_ALREADY_LISTENING => "The peer is already listening for connections.",
            P2P::PEER_E_NODE_NOT_FOUND => "The node was not found.",
            P2P::PEER_E_CONNECTION_FAILED => "The Connection attempt failed.",
            P2P::PEER_E_CONNECTION_NOT_AUTHENTICATED => "The peer connection could not be authenticated.",
            P2P::PEER_E_CONNECTION_REFUSED => "The connection was refused.",
            P2P::PEER_E_CLASSIFIER_TOO_LONG => "The peer name classifier is too long.",
            P2P::PEER_E_TOO_MANY_IDENTITIES => "The maximum number of identities have been created.",
            P2P::PEER_E_NO_KEY_ACCESS => "Unable to access a key.",
            P2P::PEER_E_GROUPS_EXIST => "The group already exists.",
            P2P::PEER_E_RECORD_NOT_FOUND => "The requested record could not be found.",
            P2P::PEER_E_DATABASE_ACCESSDENIED => "Access to the database was denied.",
            P2P::PEER_E_DBINITIALIZATION_FAILED => "The Database could not be initialized.",
            P2P::PEER_E_MAX_RECORD_SIZE_EXCEEDED => "The record is too big.",
            P2P::PEER_E_DATABASE_ALREADY_PRESENT => "The database already exists.",
            P2P::PEER_E_DATABASE_NOT_PRESENT => "The database could not be found.",
            P2P::PEER_E_IDENTITY_NOT_FOUND => "The identity could not be found.",
            P2P::PEER_E_EVENT_HANDLE_NOT_FOUND => "The event handle could not be found.",
            P2P::PEER_E_INVALID_SEARCH => "Invalid search.",
            P2P::PEER_E_INVALID_ATTRIBUTES => "The search attributes are invalid.",
            P2P::PEER_E_INVITATION_NOT_TRUSTED => "The invitation is not trusted.",
            P2P::PEER_E_CHAIN_TOO_LONG => "The certchain is too long.",
            P2P::PEER_E_INVALID_TIME_PERIOD => "The time period is invalid.",
            P2P::PEER_E_CIRCULAR_CHAIN_DETECTED => "A circular cert chain was detected.",
            P2P::PEER_E_CERT_STORE_CORRUPTED => "The certstore is corrupted.",
            P2P::PEER_E_NO_CLOUD => "The specified PNRP cloud does not exist.",
            P2P::PEER_E_CLOUD_NAME_AMBIGUOUS => "The cloud name is ambiguous.",
            P2P::PEER_E_INVALID_RECORD => "The record is invalid.",
            P2P::PEER_E_NOT_AUTHORIZED => "Not authorized.",
            P2P::PEER_E_PASSWORD_DOES_NOT_MEET_POLICY => "The password does not meet policy requirements.",
            P2P::PEER_E_DEFERRED_VALIDATION => "The record validation has been deferred.",
            P2P::PEER_E_INVALID_GROUP_PROPERTIES => "The group properties are invalid.",
            P2P::PEER_E_INVALID_PEER_NAME => "The peername is invalid.",
            P2P::PEER_E_INVALID_CLASSIFIER => "The classifier is invalid.",
            P2P::PEER_E_INVALID_FRIENDLY_NAME => "The friendly name is invalid.",
            P2P::PEER_E_INVALID_ROLE_PROPERTY => "Invalid role property.",
            P2P::PEER_E_INVALID_CLASSIFIER_PROPERTY => "Invalid classifier property.",
            P2P::PEER_E_INVALID_RECORD_EXPIRATION => "Invalid record expiration.",
            P2P::PEER_E_INVALID_CREDENTIAL_INFO => "Invalid credential info.",
            P2P::PEER_E_INVALID_CREDENTIAL => "Invalid credential.",
            P2P::PEER_E_INVALID_RECORD_SIZE => "Invalid record size.",
            P2P::PEER_E_UNSUPPORTED_VERSION => "Unsupported version.",
            P2P::PEER_E_GROUP_NOT_READY => "The group is not ready.",
            P2P::PEER_E_GROUP_IN_USE => "The group is still in use.",
            P2P::PEER_E_INVALID_GROUP => "The group is invalid.",
            P2P::PEER_E_NO_MEMBERS_FOUND => "No members were found.",
            P2P::PEER_E_NO_MEMBER_CONNECTIONS => "There are no member connections.",
            P2P::PEER_E_UNABLE_TO_LISTEN => "Unable to listen.",
            P2P::PEER_E_IDENTITY_DELETED => "The identity does not exist.",
            P2P::PEER_E_SERVICE_NOT_AVAILABLE => "The service is not available.",
            P2P::PEER_E_CANNOT_CONVERT_PEER_NAME => "The peername could not be converted to a DNS pnrp name.",
            P2P::PEER_E_INVALID_PEER_HOST_NAME => "Invalid peer host name.",
            P2P::PEER_E_NO_MORE => "No more data could be found.",
            P2P::PEER_E_PNRP_DUPLICATE_PEER_NAME => "The existing peer name is already registered.",
            P2P::PEER_E_CONTACT_NOT_FOUND => "THe contact could not be found.",
            P2P::PEER_E_INVITE_CANCELLED => "The app invite request was cancelled by the user.",
            P2P::PEER_E_INVITE_RESPONSE_NOT_AVAILABLE => "No response of the invite was received.",
            P2P::PEER_E_NOT_SIGNED_IN => "User is not signed into serverless presence.",
            P2P::PEER_E_PRIVACY_DECLINED => "The user declined the privacy policy prompt.",
            P2P::PEER_E_TIMEOUT => "A timeout occurred.",
            P2P::PEER_E_INVALID_ADDRESS => "The address is invalid.",
            P2P::PEER_E_FW_EXCEPTION_DISABLED => "A required firewall exception is disabled.",
            P2P::PEER_E_FW_BLOCKED_BY_POLICY => "The service is blocked by a firewall policy.",
            P2P::PEER_E_FW_BLOCKED_BY_SHIELDS_UP => "Firewall exceptions are disabled.",
            P2P::PEER_E_FW_DECLINED => "The user declined to enable the firewall exceptions.",
        }
    }
}
