/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum RPC_DEBUGGER {
    RPC_E_CALL_REJECTED = 0x80010001,
    RPC_E_CALL_CANCELED = 0x80010002,
    RPC_E_CANTPOST_INSENDCALL = 0x80010003,
    RPC_E_CANTCALLOUT_INASYNCCALL = 0x80010004,
    RPC_E_CANTCALLOUT_INEXTERNALCALL = 0x80010005,
    RPC_E_CONNECTION_TERMINATED = 0x80010006,
    RPC_E_SERVER_DIED = 0x80010007,
    RPC_E_CLIENT_DIED = 0x80010008,
    RPC_E_INVALID_DATAPACKET = 0x80010009,
    RPC_E_CANTTRANSMIT_CALL = 0x8001000A,
    RPC_E_CLIENT_CANTMARSHAL_DATA = 0x8001000B,
    RPC_E_CLIENT_CANTUNMARSHAL_DATA = 0x8001000C,
    RPC_E_SERVER_CANTMARSHAL_DATA = 0x8001000D,
    RPC_E_SERVER_CANTUNMARSHAL_DATA = 0x8001000E,
    RPC_E_INVALID_DATA = 0x8001000F,
    RPC_E_INVALID_PARAMETER = 0x80010010,
    RPC_E_CANTCALLOUT_AGAIN = 0x80010011,
    RPC_E_SERVER_DIED_DNE = 0x80010012,
    RPC_E_SYS_CALL_FAILED = 0x80010100,
    RPC_E_OUT_OF_RESOURCES = 0x80010101,
    RPC_E_ATTEMPTED_MULTITHREAD = 0x80010102,
    RPC_E_NOT_REGISTERED = 0x80010103,
    RPC_E_FAULT = 0x80010104,
    RPC_E_SERVERFAULT = 0x80010105,
    RPC_E_CHANGED_MODE = 0x80010106,
    RPC_E_INVALIDMETHOD = 0x80010107,
    RPC_E_DISCONNECTED = 0x80010108,
    RPC_E_RETRY = 0x80010109,
    RPC_E_SERVERCALL_RETRYLATER = 0x8001010A,
    RPC_E_SERVERCALL_REJECTED = 0x8001010B,
    RPC_E_INVALID_CALLDATA = 0x8001010C,
    RPC_E_CANTCALLOUT_ININPUTSYNCCALL = 0x8001010D,
    RPC_E_WRONG_THREAD = 0x8001010E,
    RPC_E_THREAD_NOT_INIT = 0x8001010F,
    RPC_E_VERSION_MISMATCH = 0x80010110,
    RPC_E_INVALID_HEADER = 0x80010111,
    RPC_E_INVALID_EXTENSION = 0x80010112,
    RPC_E_INVALID_IPID = 0x80010113,
    RPC_E_INVALID_OBJECT = 0x80010114,
    RPC_S_CALLPENDING = 0x80010115,
    RPC_S_WAITONTIMER = 0x80010116,
    RPC_E_CALL_COMPLETE = 0x80010117,
    RPC_E_UNSECURE_CALL = 0x80010118,
    RPC_E_TOO_LATE = 0x80010119,
    RPC_E_NO_GOOD_SECURITY_PACKAGES = 0x8001011A,
    RPC_E_ACCESS_DENIED = 0x8001011B,
    RPC_E_REMOTE_DISABLED = 0x8001011C,
    RPC_E_INVALID_OBJREF = 0x8001011D,
    RPC_E_NO_CONTEXT = 0x8001011E,
    RPC_E_TIMEOUT = 0x8001011F,
    RPC_E_NO_SYNC = 0x80010120,
    RPC_E_FULLSIC_REQUIRED = 0x80010121,
    RPC_E_INVALID_STD_NAME = 0x80010122,
    CO_E_FAILEDTOIMPERSONATE = 0x80010123,
    CO_E_FAILEDTOGETSECCTX = 0x80010124,
    CO_E_FAILEDTOOPENTHREADTOKEN = 0x80010125,
    CO_E_FAILEDTOGETTOKENINFO = 0x80010126,
    CO_E_TRUSTEEDOESNTMATCHCLIENT = 0x80010127,
    CO_E_FAILEDTOQUERYCLIENTBLANKET = 0x80010128,
    CO_E_FAILEDTOSETDACL = 0x80010129,
    CO_E_ACCESSCHECKFAILED = 0x8001012A,
    CO_E_NETACCESSAPIFAILED = 0x8001012B,
    CO_E_WRONGTRUSTEENAMESYNTAX = 0x8001012C,
    CO_E_INVALIDSID = 0x8001012D,
    CO_E_CONVERSIONFAILED = 0x8001012E,
    CO_E_NOMATCHINGSIDFOUND = 0x8001012F,
    CO_E_LOOKUPACCSIDFAILED = 0x80010130,
    CO_E_NOMATCHINGNAMEFOUND = 0x80010131,
    CO_E_LOOKUPACCNAMEFAILED = 0x80010132,
    CO_E_SETSERLHNDLFAILED = 0x80010133,
    CO_E_FAILEDTOGETWINDIR = 0x80010134,
    CO_E_PATHTOOLONG = 0x80010135,
    CO_E_FAILEDTOGENUUID = 0x80010136,
    CO_E_FAILEDTOCREATEFILE = 0x80010137,
    CO_E_FAILEDTOCLOSEHANDLE = 0x80010138,
    CO_E_EXCEEDSYSACLLIMIT = 0x80010139,
    CO_E_ACESINWRONGORDER = 0x8001013A,
    CO_E_INCOMPATIBLESTREAMVERSION = 0x8001013B,
    CO_E_FAILEDTOOPENPROCESSTOKEN = 0x8001013C,
    CO_E_DECODEFAILED = 0x8001013D,
    CO_E_ACNOTINITIALIZED = 0x8001013F,
    CO_E_CANCEL_DISABLED = 0x80010140,
    RPC_E_UNEXPECTED = 0x8001FFFF,
}

impl RPC_DEBUGGER {
    pub fn description(&self) -> &'static str {
        match self {
            RPC_DEBUGGER::RPC_E_CALL_REJECTED => "Call was rejected by callee.",
            RPC_DEBUGGER::RPC_E_CALL_CANCELED => "Call was canceled by the message filter.",
            RPC_DEBUGGER::RPC_E_CANTPOST_INSENDCALL => "The caller is dispatching an intertask SendMessage call and cannot call out via PostMessage.",
            RPC_DEBUGGER::RPC_E_CANTCALLOUT_INASYNCCALL => "The caller is dispatching an asynchronous call and cannot make an outgoing call on behalf of this call.",
            RPC_DEBUGGER::RPC_E_CANTCALLOUT_INEXTERNALCALL => "It is illegal to call out while inside message filter.",
            RPC_DEBUGGER::RPC_E_CONNECTION_TERMINATED => "The connection terminated or is in a bogus state and cannot be used any more. Other connections are still valid.",
            RPC_DEBUGGER::RPC_E_SERVER_DIED => "The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call may have executed.",
            RPC_DEBUGGER::RPC_E_CLIENT_DIED => "The caller (client) disappeared while the callee (server) was processing a call.",
            RPC_DEBUGGER::RPC_E_INVALID_DATAPACKET => "The data packet with the marshalled parameter data is incorrect.",
            RPC_DEBUGGER::RPC_E_CANTTRANSMIT_CALL => "The call was not transmitted properly; the message queue was full and was not emptied after yielding.",
            RPC_DEBUGGER::RPC_E_CLIENT_CANTMARSHAL_DATA => "The client (caller) cannot marshall the parameter data - low memory, etc.",
            RPC_DEBUGGER::RPC_E_CLIENT_CANTUNMARSHAL_DATA => "The client (caller) cannot unmarshall the return data - low memory, etc.",
            RPC_DEBUGGER::RPC_E_SERVER_CANTMARSHAL_DATA => "The server (callee) cannot marshall the return data - low memory, etc.",
            RPC_DEBUGGER::RPC_E_SERVER_CANTUNMARSHAL_DATA => "The server (callee) cannot unmarshall the parameter data - low memory, etc.",
            RPC_DEBUGGER::RPC_E_INVALID_DATA => "Received data is invalid; could be server or client data.",
            RPC_DEBUGGER::RPC_E_INVALID_PARAMETER => "A particular parameter is invalid and cannot be (un)marshalled.",
            RPC_DEBUGGER::RPC_E_CANTCALLOUT_AGAIN => "There is no second outgoing call on same channel in DDE conversation.",
            RPC_DEBUGGER::RPC_E_SERVER_DIED_DNE => "The callee (server [not server application]) is not available and disappeared; all connections are invalid. The call did not execute.",
            RPC_DEBUGGER::RPC_E_SYS_CALL_FAILED => "System call failed.",
            RPC_DEBUGGER::RPC_E_OUT_OF_RESOURCES => "Could not allocate some required resource (memory, events, ...)",
            RPC_DEBUGGER::RPC_E_ATTEMPTED_MULTITHREAD => "Attempted to make calls on more than one thread in single threaded mode.",
            RPC_DEBUGGER::RPC_E_NOT_REGISTERED => "The requested interface is not registered on the server object.",
            RPC_DEBUGGER::RPC_E_FAULT => "RPC could not call the server or could not return the results of calling the server.",
            RPC_DEBUGGER::RPC_E_SERVERFAULT => "The server threw an exception.",
            RPC_DEBUGGER::RPC_E_CHANGED_MODE => "Cannot change thread mode after it is set.",
            RPC_DEBUGGER::RPC_E_INVALIDMETHOD => "The method called does not exist on the server.",
            RPC_DEBUGGER::RPC_E_DISCONNECTED => "The object invoked has disconnected from its clients.",
            RPC_DEBUGGER::RPC_E_RETRY => "The object invoked chose not to process the call now. Try again later.",
            RPC_DEBUGGER::RPC_E_SERVERCALL_RETRYLATER => "The message filter indicated that the application is busy.",
            RPC_DEBUGGER::RPC_E_SERVERCALL_REJECTED => "The message filter rejected the call.",
            RPC_DEBUGGER::RPC_E_INVALID_CALLDATA => "A call control interfaces was called with invalid data.",
            RPC_DEBUGGER::RPC_E_CANTCALLOUT_ININPUTSYNCCALL => "An outgoing call cannot be made since the application is dispatching an input-synchronous call.",
            RPC_DEBUGGER::RPC_E_WRONG_THREAD => "The application called an interface that was marshalled for a different thread.",
            RPC_DEBUGGER::RPC_E_THREAD_NOT_INIT => "CoInitialize has not been called on the current thread.",
            RPC_DEBUGGER::RPC_E_VERSION_MISMATCH => "The version of OLE on the client and server machines does not match.",
            RPC_DEBUGGER::RPC_E_INVALID_HEADER => "OLE received a packet with an invalid header.",
            RPC_DEBUGGER::RPC_E_INVALID_EXTENSION => "OLE received a packet with an invalid extension.",
            RPC_DEBUGGER::RPC_E_INVALID_IPID => "The requested object or interface does not exist.",
            RPC_DEBUGGER::RPC_E_INVALID_OBJECT => "The requested object does not exist.",
            RPC_DEBUGGER::RPC_S_CALLPENDING => "OLE has sent a request and is waiting for a reply.",
            RPC_DEBUGGER::RPC_S_WAITONTIMER => "OLE is waiting before retrying a request.",
            RPC_DEBUGGER::RPC_E_CALL_COMPLETE => "Call context cannot be accessed after call completed.",
            RPC_DEBUGGER::RPC_E_UNSECURE_CALL => "Impersonate on unsecure calls is not supported.",
            RPC_DEBUGGER::RPC_E_TOO_LATE => "Security must be initialized before any interfaces are marshalled or unmarshalled. It cannot be changed once initialized.",
            RPC_DEBUGGER::RPC_E_NO_GOOD_SECURITY_PACKAGES => "No security packages are installed on this machine or the user is not logged on or there are no compatible security packages between the client and server.",
            RPC_DEBUGGER::RPC_E_ACCESS_DENIED => "Access is denied.",
            RPC_DEBUGGER::RPC_E_REMOTE_DISABLED => "Remote calls are not allowed for this process.",
            RPC_DEBUGGER::RPC_E_INVALID_OBJREF => "The marshaled interface data packet (OBJREF) has an invalid or unknown format.",
            RPC_DEBUGGER::RPC_E_NO_CONTEXT => "No context is associated with this call. This happens for some custom marshalled calls and on the client side of the call.",
            RPC_DEBUGGER::RPC_E_TIMEOUT => "This operation returned because the timeout period expired.",
            RPC_DEBUGGER::RPC_E_NO_SYNC => "There are no synchronize objects to wait on.",
            RPC_DEBUGGER::RPC_E_FULLSIC_REQUIRED => "Full subject issuer chain SSL principal name expected from the server.",
            RPC_DEBUGGER::RPC_E_INVALID_STD_NAME => "Principal name is not a valid MSSTD name.",
            RPC_DEBUGGER::CO_E_FAILEDTOIMPERSONATE => "Unable to impersonate DCOM client",
            RPC_DEBUGGER::CO_E_FAILEDTOGETSECCTX => "Unable to obtain server's security context",
            RPC_DEBUGGER::CO_E_FAILEDTOOPENTHREADTOKEN => "Unable to open the access token of the current thread",
            RPC_DEBUGGER::CO_E_FAILEDTOGETTOKENINFO => "Unable to obtain user info from an access token",
            RPC_DEBUGGER::CO_E_TRUSTEEDOESNTMATCHCLIENT => "The client who called IAccessControl::IsAccessPermitted was not the trustee provided to the method",
            RPC_DEBUGGER::CO_E_FAILEDTOQUERYCLIENTBLANKET => "Unable to obtain the client's security blanket",
            RPC_DEBUGGER::CO_E_FAILEDTOSETDACL => "Unable to set a discretionary ACL into a security descriptor",
            RPC_DEBUGGER::CO_E_ACCESSCHECKFAILED => "The system function, AccessCheck, returned false",
            RPC_DEBUGGER::CO_E_NETACCESSAPIFAILED => "Either NetAccessDel or NetAccessAdd returned an error code.",
            RPC_DEBUGGER::CO_E_WRONGTRUSTEENAMESYNTAX => "One of the trustee strings provided by the user did not conform to the <Domain>\<Name> syntax and it was not the ",
            RPC_DEBUGGER::CO_E_INVALIDSID => "One of the security identifiers provided by the user was invalid",
            RPC_DEBUGGER::CO_E_CONVERSIONFAILED => "Unable to convert a wide character trustee string to a multibyte trustee string",
            RPC_DEBUGGER::CO_E_NOMATCHINGSIDFOUND => "Unable to find a security identifier that corresponds to a trustee string provided by the user",
            RPC_DEBUGGER::CO_E_LOOKUPACCSIDFAILED => "The system function, LookupAccountSID, failed",
            RPC_DEBUGGER::CO_E_NOMATCHINGNAMEFOUND => "Unable to find a trustee name that corresponds to a security identifier provided by the user",
            RPC_DEBUGGER::CO_E_LOOKUPACCNAMEFAILED => "The system function, LookupAccountName, failed",
            RPC_DEBUGGER::CO_E_SETSERLHNDLFAILED => "Unable to set or reset a serialization handle",
            RPC_DEBUGGER::CO_E_FAILEDTOGETWINDIR => "Unable to obtain the Windows directory",
            RPC_DEBUGGER::CO_E_PATHTOOLONG => "Path too long",
            RPC_DEBUGGER::CO_E_FAILEDTOGENUUID => "Unable to generate a uuid.",
            RPC_DEBUGGER::CO_E_FAILEDTOCREATEFILE => "Unable to create file",
            RPC_DEBUGGER::CO_E_FAILEDTOCLOSEHANDLE => "Unable to close a serialization handle or a file handle.",
            RPC_DEBUGGER::CO_E_EXCEEDSYSACLLIMIT => "The number of ACEs in an ACL exceeds the system limit.",
            RPC_DEBUGGER::CO_E_ACESINWRONGORDER => "Not all the DENY_ACCESS ACEs are arranged in front of the GRANT_ACCESS ACEs in the stream.",
            RPC_DEBUGGER::CO_E_INCOMPATIBLESTREAMVERSION => "The version of ACL format in the stream is not supported by this implementation of IAccessControl",
            RPC_DEBUGGER::CO_E_FAILEDTOOPENPROCESSTOKEN => "Unable to open the access token of the server process",
            RPC_DEBUGGER::CO_E_DECODEFAILED => "Unable to decode the ACL in the stream provided by the user",
            RPC_DEBUGGER::CO_E_ACNOTINITIALIZED => "The COM IAccessControl object is not initialized",
            RPC_DEBUGGER::CO_E_CANCEL_DISABLED => "Call Cancellation is disabled",
            RPC_DEBUGGER::RPC_E_UNEXPECTED => "An internal error occurred.",
        }
    }
}
