/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum RPC_STUBS_STORAGE {
    STG_S_CONVERTED = 0x00030200,
    STG_S_BLOCK = 0x00030201,
    STG_S_RETRYNOW = 0x00030202,
    STG_S_MONITORING = 0x00030203,
    STG_S_MULTIPLEOPENS = 0x00030204,
    STG_S_CONSOLIDATIONFAILED = 0x00030205,
    STG_S_CANNOTCONSOLIDATE = 0x00030206,
    STG_S_POWER_CYCLE_REQUIRED = 0x00030207,
    STG_E_INVALIDFUNCTION = 0x80030001,
    STG_E_FILENOTFOUND = 0x80030002,
    STG_E_PATHNOTFOUND = 0x80030003,
    STG_E_TOOMANYOPENFILES = 0x80030004,
    STG_E_ACCESSDENIED = 0x80030005,
    STG_E_INVALIDHANDLE = 0x80030006,
    STG_E_INSUFFICIENTMEMORY = 0x80030008,
    STG_E_INVALIDPOINTER = 0x80030009,
    STG_E_NOMOREFILES = 0x80030012,
    STG_E_DISKISWRITEPROTECTED = 0x80030013,
    STG_E_SEEKERROR = 0x80030019,
    STG_E_WRITEFAULT = 0x8003001D,
    STG_E_READFAULT = 0x8003001E,
    STG_E_SHAREVIOLATION = 0x80030020,
    STG_E_LOCKVIOLATION = 0x80030021,
    STG_E_FILEALREADYEXISTS = 0x80030050,
    STG_E_INVALIDPARAMETER = 0x80030057,
    STG_E_MEDIUMFULL = 0x80030070,
    STG_E_PROPSETMISMATCHED = 0x800300F0,
    STG_E_ABNORMALAPIEXIT = 0x800300FA,
    STG_E_INVALIDHEADER = 0x800300FB,
    STG_E_INVALIDNAME = 0x800300FC,
    STG_E_UNKNOWN = 0x800300FD,
    STG_E_UNIMPLEMENTEDFUNCTION = 0x800300FE,
    STG_E_INVALIDFLAG = 0x800300FF,
    STG_E_INUSE = 0x80030100,
    STG_E_NOTCURRENT = 0x80030101,
    STG_E_REVERTED = 0x80030102,
    STG_E_CANTSAVE = 0x80030103,
    STG_E_OLDFORMAT = 0x80030104,
    STG_E_OLDDLL = 0x80030105,
    STG_E_SHAREREQUIRED = 0x80030106,
    STG_E_NOTFILEBASEDSTORAGE = 0x80030107,
    STG_E_EXTANTMARSHALLINGS = 0x80030108,
    STG_E_DOCFILECORRUPT = 0x80030109,
    STG_E_BADBASEADDRESS = 0x80030110,
    STG_E_DOCFILETOOLARGE = 0x80030111,
    STG_E_NOTSIMPLEFORMAT = 0x80030112,
    STG_E_INCOMPLETE = 0x80030201,
    STG_E_TERMINATED = 0x80030202,
    STG_E_FIRMWARE_SLOT_INVALID = 0x80030208,
    STG_E_FIRMWARE_IMAGE_INVALID = 0x80030209,
    STG_E_DEVICE_UNRESPONSIVE = 0x8003020A,
    STG_E_STATUS_COPY_PROTECTION_FAILURE = 0x80030305,
    STG_E_CSS_AUTHENTICATION_FAILURE = 0x80030306,
    STG_E_CSS_KEY_NOT_PRESENT = 0x80030307,
    STG_E_CSS_KEY_NOT_ESTABLISHED = 0x80030308,
    STG_E_CSS_SCRAMBLED_SECTOR = 0x80030309,
    STG_E_CSS_REGION_MISMATCH = 0x8003030A,
    STG_E_RESETS_EXHAUSTED = 0x8003030B,
}

impl RPC_STUBS_STORAGE {
    pub fn description(&self) -> &'static str {
        match self {
            RPC_STUBS_STORAGE::STG_S_CONVERTED => "The underlying file was converted to compound file format.",
            RPC_STUBS_STORAGE::STG_S_BLOCK => "The storage operation should block until more data is available.",
            RPC_STUBS_STORAGE::STG_S_RETRYNOW => "The storage operation should retry immediately.",
            RPC_STUBS_STORAGE::STG_S_MONITORING => "The notified event sink will not influence the storage operation.",
            RPC_STUBS_STORAGE::STG_S_MULTIPLEOPENS => "Multiple opens prevent consolidated. (commit succeeded).",
            RPC_STUBS_STORAGE::STG_S_CONSOLIDATIONFAILED => "Consolidation of the storage file failed. (commit succeeded).",
            RPC_STUBS_STORAGE::STG_S_CANNOTCONSOLIDATE => "Consolidation of the storage file is inappropriate. (commit succeeded).",
            RPC_STUBS_STORAGE::STG_S_POWER_CYCLE_REQUIRED => "The device needs to be power cycled. (commit succeeded).",
            RPC_STUBS_STORAGE::STG_E_INVALIDFUNCTION => "Unable to perform requested operation.",
            RPC_STUBS_STORAGE::STG_E_FILENOTFOUND => "%1 could not be found.",
            RPC_STUBS_STORAGE::STG_E_PATHNOTFOUND => "The path %1 could not be found.",
            RPC_STUBS_STORAGE::STG_E_TOOMANYOPENFILES => "There are insufficient resources to open another file.",
            RPC_STUBS_STORAGE::STG_E_ACCESSDENIED => "Access Denied.",
            RPC_STUBS_STORAGE::STG_E_INVALIDHANDLE => "Attempted an operation on an invalid object.",
            RPC_STUBS_STORAGE::STG_E_INSUFFICIENTMEMORY => "There is insufficient memory available to complete operation.",
            RPC_STUBS_STORAGE::STG_E_INVALIDPOINTER => "Invalid pointer error.",
            RPC_STUBS_STORAGE::STG_E_NOMOREFILES => "There are no more entries to return.",
            RPC_STUBS_STORAGE::STG_E_DISKISWRITEPROTECTED => "Disk is write-protected.",
            RPC_STUBS_STORAGE::STG_E_SEEKERROR => "An error occurred during a seek operation.",
            RPC_STUBS_STORAGE::STG_E_WRITEFAULT => "A disk error occurred during a write operation.",
            RPC_STUBS_STORAGE::STG_E_READFAULT => "A disk error occurred during a read operation.",
            RPC_STUBS_STORAGE::STG_E_SHAREVIOLATION => "A share violation has occurred.",
            RPC_STUBS_STORAGE::STG_E_LOCKVIOLATION => "A lock violation has occurred.",
            RPC_STUBS_STORAGE::STG_E_FILEALREADYEXISTS => "%1 already exists.",
            RPC_STUBS_STORAGE::STG_E_INVALIDPARAMETER => "Invalid parameter error.",
            RPC_STUBS_STORAGE::STG_E_MEDIUMFULL => "There is insufficient disk space to complete operation.",
            RPC_STUBS_STORAGE::STG_E_PROPSETMISMATCHED => "Illegal write of non-simple property to simple property set.",
            RPC_STUBS_STORAGE::STG_E_ABNORMALAPIEXIT => "An API call exited abnormally.",
            RPC_STUBS_STORAGE::STG_E_INVALIDHEADER => "The file %1 is not a valid compound file.",
            RPC_STUBS_STORAGE::STG_E_INVALIDNAME => "The name %1 is not valid.",
            RPC_STUBS_STORAGE::STG_E_UNKNOWN => "An unexpected error occurred.",
            RPC_STUBS_STORAGE::STG_E_UNIMPLEMENTEDFUNCTION => "That function is not implemented.",
            RPC_STUBS_STORAGE::STG_E_INVALIDFLAG => "Invalid flag error.",
            RPC_STUBS_STORAGE::STG_E_INUSE => "Attempted to use an object that is busy.",
            RPC_STUBS_STORAGE::STG_E_NOTCURRENT => "The storage has been changed since the last commit.",
            RPC_STUBS_STORAGE::STG_E_REVERTED => "Attempted to use an object that has ceased to exist.",
            RPC_STUBS_STORAGE::STG_E_CANTSAVE => "Can't save.",
            RPC_STUBS_STORAGE::STG_E_OLDFORMAT => "The compound file %1 was produced with an incompatible version of storage.",
            RPC_STUBS_STORAGE::STG_E_OLDDLL => "The compound file %1 was produced with a newer version of storage.",
            RPC_STUBS_STORAGE::STG_E_SHAREREQUIRED => "Share.exe or equivalent is required for operation.",
            RPC_STUBS_STORAGE::STG_E_NOTFILEBASEDSTORAGE => "Illegal operation called on non-file based storage.",
            RPC_STUBS_STORAGE::STG_E_EXTANTMARSHALLINGS => "Illegal operation called on object with extant marshallings.",
            RPC_STUBS_STORAGE::STG_E_DOCFILECORRUPT => "The docfile has been corrupted.",
            RPC_STUBS_STORAGE::STG_E_BADBASEADDRESS => "OLE32.DLL has been loaded at the wrong address.",
            RPC_STUBS_STORAGE::STG_E_DOCFILETOOLARGE => "The compound file is too large for the current implementation",
            RPC_STUBS_STORAGE::STG_E_NOTSIMPLEFORMAT => "The compound file was not created with the STGM_SIMPLE flag",
            RPC_STUBS_STORAGE::STG_E_INCOMPLETE => "The file download was aborted abnormally. The file is incomplete.",
            RPC_STUBS_STORAGE::STG_E_TERMINATED => "The file download has been terminated.",
            RPC_STUBS_STORAGE::STG_E_FIRMWARE_SLOT_INVALID => "The specified firmware slot is invalid.",
            RPC_STUBS_STORAGE::STG_E_FIRMWARE_IMAGE_INVALID => "The specified firmware image is invalid.",
            RPC_STUBS_STORAGE::STG_E_DEVICE_UNRESPONSIVE => "The storage device is unresponsive.",
            RPC_STUBS_STORAGE::STG_E_STATUS_COPY_PROTECTION_FAILURE => "Generic Copy Protection Error.",
            RPC_STUBS_STORAGE::STG_E_CSS_AUTHENTICATION_FAILURE => "Copy Protection Error - DVD CSS Authentication failed.",
            RPC_STUBS_STORAGE::STG_E_CSS_KEY_NOT_PRESENT => "Copy Protection Error - The given sector does not have a valid CSS key.",
            RPC_STUBS_STORAGE::STG_E_CSS_KEY_NOT_ESTABLISHED => "Copy Protection Error - DVD session key not established.",
            RPC_STUBS_STORAGE::STG_E_CSS_SCRAMBLED_SECTOR => "Copy Protection Error - The read failed because the sector is encrypted.",
            RPC_STUBS_STORAGE::STG_E_CSS_REGION_MISMATCH => "Copy Protection Error - The current DVD's region does not correspond to the region setting of the drive.",
            RPC_STUBS_STORAGE::STG_E_RESETS_EXHAUSTED => "Copy Protection Error - The drive's region setting may be permanent or the number of user resets has been exhausted.",
        }
    }
}
