/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum SETUPAPI {
    SPAPI_E_EXPECTED_SECTION_NAME = 0x800F0000,
    SPAPI_E_BAD_SECTION_NAME_LINE = 0x800F0001,
    SPAPI_E_SECTION_NAME_TOO_LONG = 0x800F0002,
    SPAPI_E_GENERAL_SYNTAX = 0x800F0003,
    SPAPI_E_WRONG_INF_STYLE = 0x800F0100,
    SPAPI_E_SECTION_NOT_FOUND = 0x800F0101,
    SPAPI_E_LINE_NOT_FOUND = 0x800F0102,
    SPAPI_E_NO_BACKUP = 0x800F0103,
    SPAPI_E_NO_ASSOCIATED_CLASS = 0x800F0200,
    SPAPI_E_CLASS_MISMATCH = 0x800F0201,
    SPAPI_E_DUPLICATE_FOUND = 0x800F0202,
    SPAPI_E_NO_DRIVER_SELECTED = 0x800F0203,
    SPAPI_E_KEY_DOES_NOT_EXIST = 0x800F0204,
    SPAPI_E_INVALID_DEVINST_NAME = 0x800F0205,
    SPAPI_E_INVALID_CLASS = 0x800F0206,
    SPAPI_E_DEVINST_ALREADY_EXISTS = 0x800F0207,
    SPAPI_E_DEVINFO_NOT_REGISTERED = 0x800F0208,
    SPAPI_E_INVALID_REG_PROPERTY = 0x800F0209,
    SPAPI_E_NO_INF = 0x800F020A,
    SPAPI_E_NO_SUCH_DEVINST = 0x800F020B,
    SPAPI_E_CANT_LOAD_CLASS_ICON = 0x800F020C,
    SPAPI_E_INVALID_CLASS_INSTALLER = 0x800F020D,
    SPAPI_E_DI_DO_DEFAULT = 0x800F020E,
    SPAPI_E_DI_NOFILECOPY = 0x800F020F,
    SPAPI_E_INVALID_HWPROFILE = 0x800F0210,
    SPAPI_E_NO_DEVICE_SELECTED = 0x800F0211,
    SPAPI_E_DEVINFO_LIST_LOCKED = 0x800F0212,
    SPAPI_E_DEVINFO_DATA_LOCKED = 0x800F0213,
    SPAPI_E_DI_BAD_PATH = 0x800F0214,
    SPAPI_E_NO_CLASSINSTALL_PARAMS = 0x800F0215,
    SPAPI_E_FILEQUEUE_LOCKED = 0x800F0216,
    SPAPI_E_BAD_SERVICE_INSTALLSECT = 0x800F0217,
    SPAPI_E_NO_CLASS_DRIVER_LIST = 0x800F0218,
    SPAPI_E_NO_ASSOCIATED_SERVICE = 0x800F0219,
    SPAPI_E_NO_DEFAULT_DEVICE_INTERFACE = 0x800F021A,
    SPAPI_E_DEVICE_INTERFACE_ACTIVE = 0x800F021B,
    SPAPI_E_DEVICE_INTERFACE_REMOVED = 0x800F021C,
    SPAPI_E_BAD_INTERFACE_INSTALLSECT = 0x800F021D,
    SPAPI_E_NO_SUCH_INTERFACE_CLASS = 0x800F021E,
    SPAPI_E_INVALID_REFERENCE_STRING = 0x800F021F,
    SPAPI_E_INVALID_MACHINENAME = 0x800F0220,
    SPAPI_E_REMOTE_COMM_FAILURE = 0x800F0221,
    SPAPI_E_MACHINE_UNAVAILABLE = 0x800F0222,
    SPAPI_E_NO_CONFIGMGR_SERVICES = 0x800F0223,
    SPAPI_E_INVALID_PROPPAGE_PROVIDER = 0x800F0224,
    SPAPI_E_NO_SUCH_DEVICE_INTERFACE = 0x800F0225,
    SPAPI_E_DI_POSTPROCESSING_REQUIRED = 0x800F0226,
    SPAPI_E_INVALID_COINSTALLER = 0x800F0227,
    SPAPI_E_NO_COMPAT_DRIVERS = 0x800F0228,
    SPAPI_E_NO_DEVICE_ICON = 0x800F0229,
    SPAPI_E_INVALID_INF_LOGCONFIG = 0x800F022A,
    SPAPI_E_DI_DONT_INSTALL = 0x800F022B,
    SPAPI_E_INVALID_FILTER_DRIVER = 0x800F022C,
    SPAPI_E_NON_WINDOWS_NT_DRIVER = 0x800F022D,
    SPAPI_E_NON_WINDOWS_DRIVER = 0x800F022E,
    SPAPI_E_NO_CATALOG_FOR_OEM_INF = 0x800F022F,
    SPAPI_E_DEVINSTALL_QUEUE_NONNATIVE = 0x800F0230,
    SPAPI_E_NOT_DISABLEABLE = 0x800F0231,
    SPAPI_E_CANT_REMOVE_DEVINST = 0x800F0232,
    SPAPI_E_INVALID_TARGET = 0x800F0233,
    SPAPI_E_DRIVER_NONNATIVE = 0x800F0234,
    SPAPI_E_IN_WOW64 = 0x800F0235,
    SPAPI_E_SET_SYSTEM_RESTORE_POINT = 0x800F0236,
    SPAPI_E_INCORRECTLY_COPIED_INF = 0x800F0237,
    SPAPI_E_SCE_DISABLED = 0x800F0238,
    SPAPI_E_UNKNOWN_EXCEPTION = 0x800F0239,
    SPAPI_E_PNP_REGISTRY_ERROR = 0x800F023A,
    SPAPI_E_REMOTE_REQUEST_UNSUPPORTED = 0x800F023B,
    SPAPI_E_NOT_AN_INSTALLED_OEM_INF = 0x800F023C,
    SPAPI_E_INF_IN_USE_BY_DEVICES = 0x800F023D,
    SPAPI_E_DI_FUNCTION_OBSOLETE = 0x800F023E,
    SPAPI_E_NO_AUTHENTICODE_CATALOG = 0x800F023F,
    SPAPI_E_AUTHENTICODE_DISALLOWED = 0x800F0240,
    SPAPI_E_AUTHENTICODE_TRUSTED_PUBLISHER = 0x800F0241,
    SPAPI_E_AUTHENTICODE_TRUST_NOT_ESTABLISHED = 0x800F0242,
    SPAPI_E_AUTHENTICODE_PUBLISHER_NOT_TRUSTED = 0x800F0243,
    SPAPI_E_SIGNATURE_OSATTRIBUTE_MISMATCH = 0x800F0244,
    SPAPI_E_ONLY_VALIDATE_VIA_AUTHENTICODE = 0x800F0245,
    SPAPI_E_DEVICE_INSTALLER_NOT_READY = 0x800F0246,
    SPAPI_E_DRIVER_STORE_ADD_FAILED = 0x800F0247,
    SPAPI_E_DEVICE_INSTALL_BLOCKED = 0x800F0248,
    SPAPI_E_DRIVER_INSTALL_BLOCKED = 0x800F0249,
    SPAPI_E_WRONG_INF_TYPE = 0x800F024A,
    SPAPI_E_FILE_HASH_NOT_IN_CATALOG = 0x800F024B,
    SPAPI_E_DRIVER_STORE_DELETE_FAILED = 0x800F024C,
    SPAPI_E_UNRECOVERABLE_STACK_OVERFLOW = 0x800F0300,
    SPAPI_E_ERROR_NOT_INSTALLED = 0x800F1000,
}

impl SETUPAPI {
    pub fn description(&self) -> &'static str {
        match self {
            SETUPAPI::SPAPI_E_EXPECTED_SECTION_NAME => "A non-empty line was encountered in the INF before the start of a section.",
            SETUPAPI::SPAPI_E_BAD_SECTION_NAME_LINE => "A section name marker in the INF is not complete, or does not exist on a line by itself.",
            SETUPAPI::SPAPI_E_SECTION_NAME_TOO_LONG => "An INF section was encountered whose name exceeds the maximum section name length.",
            SETUPAPI::SPAPI_E_GENERAL_SYNTAX => "The syntax of the INF is invalid.",
            SETUPAPI::SPAPI_E_WRONG_INF_STYLE => "The style of the INF is different than what was requested.",
            SETUPAPI::SPAPI_E_SECTION_NOT_FOUND => "The required section was not found in the INF.",
            SETUPAPI::SPAPI_E_LINE_NOT_FOUND => "The required line was not found in the INF.",
            SETUPAPI::SPAPI_E_NO_BACKUP => "The files affected by the installation of this file queue have not been backed up for uninstall.",
            SETUPAPI::SPAPI_E_NO_ASSOCIATED_CLASS => "The INF or the device information set or element does not have an associated install class.",
            SETUPAPI::SPAPI_E_CLASS_MISMATCH => "The INF or the device information set or element does not match the specified install class.",
            SETUPAPI::SPAPI_E_DUPLICATE_FOUND => "An existing device was found that is a duplicate of the device being manually installed.",
            SETUPAPI::SPAPI_E_NO_DRIVER_SELECTED => "There is no driver selected for the device information set or element.",
            SETUPAPI::SPAPI_E_KEY_DOES_NOT_EXIST => "The requested device registry key does not exist.",
            SETUPAPI::SPAPI_E_INVALID_DEVINST_NAME => "The device instance name is invalid.",
            SETUPAPI::SPAPI_E_INVALID_CLASS => "The install class is not present or is invalid.",
            SETUPAPI::SPAPI_E_DEVINST_ALREADY_EXISTS => "The device instance cannot be created because it already exists.",
            SETUPAPI::SPAPI_E_DEVINFO_NOT_REGISTERED => "The operation cannot be performed on a device information element that has not been registered.",
            SETUPAPI::SPAPI_E_INVALID_REG_PROPERTY => "The device property code is invalid.",
            SETUPAPI::SPAPI_E_NO_INF => "The INF from which a driver list is to be built does not exist.",
            SETUPAPI::SPAPI_E_NO_SUCH_DEVINST => "The device instance does not exist in the hardware tree.",
            SETUPAPI::SPAPI_E_CANT_LOAD_CLASS_ICON => "The icon representing this install class cannot be loaded.",
            SETUPAPI::SPAPI_E_INVALID_CLASS_INSTALLER => "The class installer registry entry is invalid.",
            SETUPAPI::SPAPI_E_DI_DO_DEFAULT => "The class installer has indicated that the default action should be performed for this installation request.",
            SETUPAPI::SPAPI_E_DI_NOFILECOPY => "The operation does not require any files to be copied.",
            SETUPAPI::SPAPI_E_INVALID_HWPROFILE => "The specified hardware profile does not exist.",
            SETUPAPI::SPAPI_E_NO_DEVICE_SELECTED => "There is no device information element currently selected for this device information set.",
            SETUPAPI::SPAPI_E_DEVINFO_LIST_LOCKED => "The operation cannot be performed because the device information set is locked.",
            SETUPAPI::SPAPI_E_DEVINFO_DATA_LOCKED => "The operation cannot be performed because the device information element is locked.",
            SETUPAPI::SPAPI_E_DI_BAD_PATH => "The specified path does not contain any applicable device INFs.",
            SETUPAPI::SPAPI_E_NO_CLASSINSTALL_PARAMS => "No class installer parameters have been set for the device information set or element.",
            SETUPAPI::SPAPI_E_FILEQUEUE_LOCKED => "The operation cannot be performed because the file queue is locked.",
            SETUPAPI::SPAPI_E_BAD_SERVICE_INSTALLSECT => "A service installation section in this INF is invalid.",
            SETUPAPI::SPAPI_E_NO_CLASS_DRIVER_LIST => "There is no class driver list for the device information element.",
            SETUPAPI::SPAPI_E_NO_ASSOCIATED_SERVICE => "The installation failed because a function driver was not specified for this device instance.",
            SETUPAPI::SPAPI_E_NO_DEFAULT_DEVICE_INTERFACE => "There is presently no default device interface designated for this interface class.",
            SETUPAPI::SPAPI_E_DEVICE_INTERFACE_ACTIVE => "The operation cannot be performed because the device interface is currently active.",
            SETUPAPI::SPAPI_E_DEVICE_INTERFACE_REMOVED => "The operation cannot be performed because the device interface has been removed from the system.",
            SETUPAPI::SPAPI_E_BAD_INTERFACE_INSTALLSECT => "An interface installation section in this INF is invalid.",
            SETUPAPI::SPAPI_E_NO_SUCH_INTERFACE_CLASS => "This interface class does not exist in the system.",
            SETUPAPI::SPAPI_E_INVALID_REFERENCE_STRING => "The reference string supplied for this interface device is invalid.",
            SETUPAPI::SPAPI_E_INVALID_MACHINENAME => "The specified machine name does not conform to UNC naming conventions.",
            SETUPAPI::SPAPI_E_REMOTE_COMM_FAILURE => "A general remote communication error occurred.",
            SETUPAPI::SPAPI_E_MACHINE_UNAVAILABLE => "The machine selected for remote communication is not available at this time.",
            SETUPAPI::SPAPI_E_NO_CONFIGMGR_SERVICES => "The Plug and Play service is not available on the remote machine.",
            SETUPAPI::SPAPI_E_INVALID_PROPPAGE_PROVIDER => "The property page provider registry entry is invalid.",
            SETUPAPI::SPAPI_E_NO_SUCH_DEVICE_INTERFACE => "The requested device interface is not present in the system.",
            SETUPAPI::SPAPI_E_DI_POSTPROCESSING_REQUIRED => "The device's co-installer has additional work to perform after installation is complete.",
            SETUPAPI::SPAPI_E_INVALID_COINSTALLER => "The device's co-installer is invalid.",
            SETUPAPI::SPAPI_E_NO_COMPAT_DRIVERS => "There are no compatible drivers for this device.",
            SETUPAPI::SPAPI_E_NO_DEVICE_ICON => "There is no icon that represents this device or device type.",
            SETUPAPI::SPAPI_E_INVALID_INF_LOGCONFIG => "A logical configuration specified in this INF is invalid.",
            SETUPAPI::SPAPI_E_DI_DONT_INSTALL => "The class installer has denied the request to install or upgrade this device.",
            SETUPAPI::SPAPI_E_INVALID_FILTER_DRIVER => "One of the filter drivers installed for this device is invalid.",
            SETUPAPI::SPAPI_E_NON_WINDOWS_NT_DRIVER => "The driver selected for this device does not support this version of Windows.",
            SETUPAPI::SPAPI_E_NON_WINDOWS_DRIVER => "The driver selected for this device does not support Windows.",
            SETUPAPI::SPAPI_E_NO_CATALOG_FOR_OEM_INF => "The third-party INF does not contain digital signature information.",
            SETUPAPI::SPAPI_E_DEVINSTALL_QUEUE_NONNATIVE => "An invalid attempt was made to use a device installation file queue for verification of digital signatures relative to other platforms.",
            SETUPAPI::SPAPI_E_NOT_DISABLEABLE => "The device cannot be disabled.",
            SETUPAPI::SPAPI_E_CANT_REMOVE_DEVINST => "The device could not be dynamically removed.",
            SETUPAPI::SPAPI_E_INVALID_TARGET => "Cannot copy to specified target.",
            SETUPAPI::SPAPI_E_DRIVER_NONNATIVE => "Driver is not intended for this platform.",
            SETUPAPI::SPAPI_E_IN_WOW64 => "Operation not allowed in WOW64.",
            SETUPAPI::SPAPI_E_SET_SYSTEM_RESTORE_POINT => "The operation involving unsigned file copying was rolled back, so that a system restore point could be set.",
            SETUPAPI::SPAPI_E_INCORRECTLY_COPIED_INF => "An INF was copied into the Windows INF directory in an improper manner.",
            SETUPAPI::SPAPI_E_SCE_DISABLED => "The Security Configuration Editor (SCE) APIs have been disabled on this Embedded product.",
            SETUPAPI::SPAPI_E_UNKNOWN_EXCEPTION => "An unknown exception was encountered.",
            SETUPAPI::SPAPI_E_PNP_REGISTRY_ERROR => "A problem was encountered when accessing the Plug and Play registry database.",
            SETUPAPI::SPAPI_E_REMOTE_REQUEST_UNSUPPORTED => "The requested operation is not supported for a remote machine.",
            SETUPAPI::SPAPI_E_NOT_AN_INSTALLED_OEM_INF => "The specified file is not an installed OEM INF.",
            SETUPAPI::SPAPI_E_INF_IN_USE_BY_DEVICES => "One or more devices are presently installed using the specified INF.",
            SETUPAPI::SPAPI_E_DI_FUNCTION_OBSOLETE => "The requested device install operation is obsolete.",
            SETUPAPI::SPAPI_E_NO_AUTHENTICODE_CATALOG => "A file could not be verified because it does not have an associated catalog signed via Authenticode(tm).",
            SETUPAPI::SPAPI_E_AUTHENTICODE_DISALLOWED => "Authenticode(tm) signature verification is not supported for the specified INF.",
            SETUPAPI::SPAPI_E_AUTHENTICODE_TRUSTED_PUBLISHER => "The INF was signed with an Authenticode(tm) catalog from a trusted publisher.",
            SETUPAPI::SPAPI_E_AUTHENTICODE_TRUST_NOT_ESTABLISHED => "The publisher of an Authenticode(tm) signed catalog has not yet been established as trusted.",
            SETUPAPI::SPAPI_E_AUTHENTICODE_PUBLISHER_NOT_TRUSTED => "The publisher of an Authenticode(tm) signed catalog was not established as trusted.",
            SETUPAPI::SPAPI_E_SIGNATURE_OSATTRIBUTE_MISMATCH => "The software was tested for compliance with Windows Logo requirements on a different version of Windows, and may not be compatible with this version.",
            SETUPAPI::SPAPI_E_ONLY_VALIDATE_VIA_AUTHENTICODE => "The file may only be validated by a catalog signed via Authenticode(tm).",
            SETUPAPI::SPAPI_E_DEVICE_INSTALLER_NOT_READY => "One of the installers for this device cannot perform the installation at this time.",
            SETUPAPI::SPAPI_E_DRIVER_STORE_ADD_FAILED => "A problem was encountered while attempting to add the driver to the store.",
            SETUPAPI::SPAPI_E_DEVICE_INSTALL_BLOCKED => "The installation of this device is forbidden by system policy. Contact your system administrator.",
            SETUPAPI::SPAPI_E_DRIVER_INSTALL_BLOCKED => "The installation of this driver is forbidden by system policy. Contact your system administrator.",
            SETUPAPI::SPAPI_E_WRONG_INF_TYPE => "The specified INF is the wrong type for this operation.",
            SETUPAPI::SPAPI_E_FILE_HASH_NOT_IN_CATALOG => "The hash for the file is not present in the specified catalog file. The file is likely corrupt or the victim of tampering.",
            SETUPAPI::SPAPI_E_DRIVER_STORE_DELETE_FAILED => "A problem was encountered while attempting to delete the driver from the store.",
            SETUPAPI::SPAPI_E_UNRECOVERABLE_STACK_OVERFLOW => "An unrecoverable stack overflow was encountered.",
            SETUPAPI::SPAPI_E_ERROR_NOT_INSTALLED => "No installed components were detected.",
        }
    }
}
