/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum SIP_STATUS_CODE {
    RTC_E_STATUS_INFO_TRYING = 0x00EF0064,
    RTC_E_STATUS_INFO_RINGING = 0x00EF00B4,
    RTC_E_STATUS_INFO_CALL_FORWARDING = 0x00EF00B5,
    RTC_E_STATUS_INFO_QUEUED = 0x00EF00B6,
    RTC_E_STATUS_SESSION_PROGRESS = 0x00EF00B7,
    RTC_E_STATUS_SUCCESS = 0x00EF00C8,
    RTC_E_STATUS_REDIRECT_MULTIPLE_CHOICES = 0x80EF012C,
    RTC_E_STATUS_REDIRECT_MOVED_PERMANENTLY = 0x80EF012D,
    RTC_E_STATUS_REDIRECT_MOVED_TEMPORARILY = 0x80EF012E,
    RTC_E_STATUS_REDIRECT_SEE_OTHER = 0x80EF012F,
    RTC_E_STATUS_REDIRECT_USE_PROXY = 0x80EF0131,
    RTC_E_STATUS_REDIRECT_ALTERNATIVE_SERVICE = 0x80EF017C,
    RTC_E_STATUS_CLIENT_BAD_REQUEST = 0x80EF0190,
    RTC_E_STATUS_CLIENT_UNAUTHORIZED = 0x80EF0191,
    RTC_E_STATUS_CLIENT_PAYMENT_REQUIRED = 0x80EF0192,
    RTC_E_STATUS_CLIENT_FORBIDDEN = 0x80EF0193,
    RTC_E_STATUS_CLIENT_NOT_FOUND = 0x80EF0194,
    RTC_E_STATUS_CLIENT_METHOD_NOT_ALLOWED = 0x80EF0195,
    RTC_E_STATUS_CLIENT_NOT_ACCEPTABLE = 0x80EF0196,
    RTC_E_STATUS_CLIENT_PROXY_AUTHENTICATION_REQUIRED = 0x80EF0197,
    RTC_E_STATUS_CLIENT_REQUEST_TIMEOUT = 0x80EF0198,
    RTC_E_STATUS_CLIENT_CONFLICT = 0x80EF0199,
    RTC_E_STATUS_CLIENT_GONE = 0x80EF019A,
    RTC_E_STATUS_CLIENT_LENGTH_REQUIRED = 0x80EF019B,
    RTC_E_STATUS_CLIENT_REQUEST_ENTITY_TOO_LARGE = 0x80EF019D,
    RTC_E_STATUS_CLIENT_REQUEST_URI_TOO_LARGE = 0x80EF019E,
    RTC_E_STATUS_CLIENT_UNSUPPORTED_MEDIA_TYPE = 0x80EF019F,
    RTC_E_STATUS_CLIENT_BAD_EXTENSION = 0x80EF01A4,
    RTC_E_STATUS_CLIENT_TEMPORARILY_NOT_AVAILABLE = 0x80EF01E0,
    RTC_E_STATUS_CLIENT_TRANSACTION_DOES_NOT_EXIST = 0x80EF01E1,
    RTC_E_STATUS_CLIENT_LOOP_DETECTED = 0x80EF01E2,
    RTC_E_STATUS_CLIENT_TOO_MANY_HOPS = 0x80EF01E3,
    RTC_E_STATUS_CLIENT_ADDRESS_INCOMPLETE = 0x80EF01E4,
    RTC_E_STATUS_CLIENT_AMBIGUOUS = 0x80EF01E5,
    RTC_E_STATUS_CLIENT_BUSY_HERE = 0x80EF01E6,
    RTC_E_STATUS_REQUEST_TERMINATED = 0x80EF01E7,
    RTC_E_STATUS_NOT_ACCEPTABLE_HERE = 0x80EF01E8,
    RTC_E_STATUS_SERVER_INTERNAL_ERROR = 0x80EF01F4,
    RTC_E_STATUS_SERVER_NOT_IMPLEMENTED = 0x80EF01F5,
    RTC_E_STATUS_SERVER_BAD_GATEWAY = 0x80EF01F6,
    RTC_E_STATUS_SERVER_SERVICE_UNAVAILABLE = 0x80EF01F7,
    RTC_E_STATUS_SERVER_SERVER_TIMEOUT = 0x80EF01F8,
    RTC_E_STATUS_SERVER_VERSION_NOT_SUPPORTED = 0x80EF01F9,
    RTC_E_STATUS_GLOBAL_BUSY_EVERYWHERE = 0x80EF0258,
    RTC_E_STATUS_GLOBAL_DECLINE = 0x80EF025B,
    RTC_E_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE = 0x80EF025C,
    RTC_E_STATUS_GLOBAL_NOT_ACCEPTABLE = 0x80EF025E,
}

impl SIP_STATUS_CODE {
    pub fn description(&self) -> &'static str {
        match self {
            SIP_STATUS_CODE::RTC_E_STATUS_INFO_TRYING => "Trying",
            SIP_STATUS_CODE::RTC_E_STATUS_INFO_RINGING => "Ringing",
            SIP_STATUS_CODE::RTC_E_STATUS_INFO_CALL_FORWARDING => "Call Is Being Forwarded",
            SIP_STATUS_CODE::RTC_E_STATUS_INFO_QUEUED => "Queued",
            SIP_STATUS_CODE::RTC_E_STATUS_SESSION_PROGRESS => "Session Progress",
            SIP_STATUS_CODE::RTC_E_STATUS_SUCCESS => "OK",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_MULTIPLE_CHOICES => "Multiple Choices",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_MOVED_PERMANENTLY => "Moved Permanently",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_MOVED_TEMPORARILY => "Moved Temporarily",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_SEE_OTHER => "See Other",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_USE_PROXY => "Use Proxy",
            SIP_STATUS_CODE::RTC_E_STATUS_REDIRECT_ALTERNATIVE_SERVICE => "Alternative Service",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_BAD_REQUEST => "Bad Request",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_UNAUTHORIZED => "Unauthorized",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_PAYMENT_REQUIRED => "Payment Required",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_FORBIDDEN => "Forbidden",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_NOT_FOUND => "Not Found",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_METHOD_NOT_ALLOWED => "Method Not Allowed",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_NOT_ACCEPTABLE => "Not Acceptable",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_PROXY_AUTHENTICATION_REQUIRED => "Proxy Authentication Required",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_REQUEST_TIMEOUT => "Request Timeout",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_CONFLICT => "Conflict",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_GONE => "Gone",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_LENGTH_REQUIRED => "Length Required",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_REQUEST_ENTITY_TOO_LARGE => "Request Entity Too Large",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_REQUEST_URI_TOO_LARGE => "Request-URI Too Long",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_UNSUPPORTED_MEDIA_TYPE => "Unsupported Media Type",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_BAD_EXTENSION => "Bad Extension",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_TEMPORARILY_NOT_AVAILABLE => "Temporarily Unavailable",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_TRANSACTION_DOES_NOT_EXIST => "Call Leg/Transaction Does Not Exist",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_LOOP_DETECTED => "Loop Detected",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_TOO_MANY_HOPS => "Too Many Hops",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_ADDRESS_INCOMPLETE => "Address Incomplete",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_AMBIGUOUS => "Ambiguous",
            SIP_STATUS_CODE::RTC_E_STATUS_CLIENT_BUSY_HERE => "Busy Here",
            SIP_STATUS_CODE::RTC_E_STATUS_REQUEST_TERMINATED => "Request Terminated",
            SIP_STATUS_CODE::RTC_E_STATUS_NOT_ACCEPTABLE_HERE => "Not Acceptable Here",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_INTERNAL_ERROR => "Server Internal Error",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_NOT_IMPLEMENTED => "Not Implemented",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_BAD_GATEWAY => "Bad Gateway",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_SERVICE_UNAVAILABLE => "Service Unavailable",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_SERVER_TIMEOUT => "Server Time-out",
            SIP_STATUS_CODE::RTC_E_STATUS_SERVER_VERSION_NOT_SUPPORTED => "Version Not Supported",
            SIP_STATUS_CODE::RTC_E_STATUS_GLOBAL_BUSY_EVERYWHERE => "Busy Everywhere",
            SIP_STATUS_CODE::RTC_E_STATUS_GLOBAL_DECLINE => "Decline",
            SIP_STATUS_CODE::RTC_E_STATUS_GLOBAL_DOES_NOT_EXIST_ANYWHERE => "Does Not Exist Anywhere",
            SIP_STATUS_CODE::RTC_E_STATUS_GLOBAL_NOT_ACCEPTABLE => "Not Acceptable",
        }
    }
}
