/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum USERMODE_HYPERVISOR {
    ERROR_HV_PENDING_PAGE_REQUESTS = 0x00350059,
    ERROR_HV_INVALID_HYPERCALL_CODE = 0xC0350002,
    ERROR_HV_INVALID_HYPERCALL_INPUT = 0xC0350003,
    ERROR_HV_INVALID_ALIGNMENT = 0xC0350004,
    ERROR_HV_INVALID_PARAMETER = 0xC0350005,
    ERROR_HV_ACCESS_DENIED = 0xC0350006,
    ERROR_HV_INVALID_PARTITION_STATE = 0xC0350007,
    ERROR_HV_OPERATION_DENIED = 0xC0350008,
    ERROR_HV_UNKNOWN_PROPERTY = 0xC0350009,
    ERROR_HV_PROPERTY_VALUE_OUT_OF_RANGE = 0xC035000A,
    ERROR_HV_INSUFFICIENT_MEMORY = 0xC035000B,
    ERROR_HV_PARTITION_TOO_DEEP = 0xC035000C,
    ERROR_HV_INVALID_PARTITION_ID = 0xC035000D,
    ERROR_HV_INVALID_VP_INDEX = 0xC035000E,
    ERROR_HV_INVALID_PORT_ID = 0xC0350011,
    ERROR_HV_INVALID_CONNECTION_ID = 0xC0350012,
    ERROR_HV_INSUFFICIENT_BUFFERS = 0xC0350013,
    ERROR_HV_NOT_ACKNOWLEDGED = 0xC0350014,
    ERROR_HV_INVALID_VP_STATE = 0xC0350015,
    ERROR_HV_ACKNOWLEDGED = 0xC0350016,
    ERROR_HV_INVALID_SAVE_RESTORE_STATE = 0xC0350017,
    ERROR_HV_INVALID_SYNIC_STATE = 0xC0350018,
    ERROR_HV_OBJECT_IN_USE = 0xC0350019,
    ERROR_HV_INVALID_PROXIMITY_DOMAIN_INFO = 0xC035001A,
    ERROR_HV_NO_DATA = 0xC035001B,
    ERROR_HV_INACTIVE = 0xC035001C,
    ERROR_HV_NO_RESOURCES = 0xC035001D,
    ERROR_HV_FEATURE_UNAVAILABLE = 0xC035001E,
    ERROR_HV_INSUFFICIENT_BUFFER = 0xC0350033,
    ERROR_HV_INSUFFICIENT_DEVICE_DOMAINS = 0xC0350038,
    ERROR_HV_CPUID_FEATURE_VALIDATION = 0xC035003C,
    ERROR_HV_CPUID_XSAVE_FEATURE_VALIDATION = 0xC035003D,
    ERROR_HV_PROCESSOR_STARTUP_TIMEOUT = 0xC035003E,
    ERROR_HV_SMX_ENABLED = 0xC035003F,
    ERROR_HV_INVALID_LP_INDEX = 0xC0350041,
    ERROR_HV_INVALID_REGISTER_VALUE = 0xC0350050,
    ERROR_HV_INVALID_VTL_STATE = 0xC0350051,
    ERROR_HV_NX_NOT_DETECTED = 0xC0350055,
    ERROR_HV_INVALID_DEVICE_ID = 0xC0350057,
    ERROR_HV_INVALID_DEVICE_STATE = 0xC0350058,
    ERROR_HV_PAGE_REQUEST_INVALID = 0xC0350060,
    ERROR_HV_INVALID_CPU_GROUP_ID = 0xC035006F,
    ERROR_HV_INVALID_CPU_GROUP_STATE = 0xC0350070,
    ERROR_HV_OPERATION_FAILED = 0xC0350071,
    ERROR_HV_NOT_ALLOWED_WITH_NESTED_VIRT_ACTIVE = 0xC0350072,
    ERROR_HV_INSUFFICIENT_ROOT_MEMORY = 0xC0350073,
    ERROR_HV_EVENT_BUFFER_ALREADY_FREED = 0xC0350074,
    ERROR_HV_INSUFFICIENT_CONTIGUOUS_MEMORY = 0xC0350075,
    ERROR_HV_DEVICE_NOT_IN_DOMAIN = 0xC0350076,
    ERROR_HV_NESTED_VM_EXIT = 0xC0350077,
    ERROR_HV_MSR_ACCESS_FAILED = 0xC0350080,
    ERROR_HV_INSUFFICIENT_MEMORY_MIRRORING = 0xC0350081,
    ERROR_HV_INSUFFICIENT_CONTIGUOUS_MEMORY_MIRRORING = 0xC0350082,
    ERROR_HV_INSUFFICIENT_CONTIGUOUS_ROOT_MEMORY = 0xC0350083,
    ERROR_HV_INSUFFICIENT_ROOT_MEMORY_MIRRORING = 0xC0350084,
    ERROR_HV_INSUFFICIENT_CONTIGUOUS_ROOT_MEMORY_MIRRORING = 0xC0350085,
    ERROR_HV_NOT_PRESENT = 0xC0351000,
}

impl USERMODE_HYPERVISOR {
    pub fn description(&self) -> &'static str {
        match self {
            USERMODE_HYPERVISOR::ERROR_HV_PENDING_PAGE_REQUESTS => "The device had pending page requests which were discarded.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_HYPERCALL_CODE => "The hypervisor does not support the operation because the specified hypercall code is not supported.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_HYPERCALL_INPUT => "The hypervisor does not support the operation because the encoding for the hypercall input register is not supported.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_ALIGNMENT => "The hypervisor could not perform the operation because a parameter has an invalid alignment.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_PARAMETER => "The hypervisor could not perform the operation because an invalid parameter was specified.",
            USERMODE_HYPERVISOR::ERROR_HV_ACCESS_DENIED => "Access to the specified object was denied.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_PARTITION_STATE => "The hypervisor could not perform the operation because the partition is entering or in an invalid state.",
            USERMODE_HYPERVISOR::ERROR_HV_OPERATION_DENIED => "The operation is not allowed in the current state.",
            USERMODE_HYPERVISOR::ERROR_HV_UNKNOWN_PROPERTY => "The hypervisor does not recognize the specified partition property.",
            USERMODE_HYPERVISOR::ERROR_HV_PROPERTY_VALUE_OUT_OF_RANGE => "The specified value of a partition property is out of range or violates an invariant.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_MEMORY => "There is not enough memory in the hypervisor pool to complete the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_PARTITION_TOO_DEEP => "The maximum partition depth has been exceeded for the partition hierarchy.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_PARTITION_ID => "A partition with the specified partition Id does not exist.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_VP_INDEX => "The hypervisor could not perform the operation because the specified VP index is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_PORT_ID => "The hypervisor could not perform the operation because the specified port identifier is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_CONNECTION_ID => "The hypervisor could not perform the operation because the specified connection identifier is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_BUFFERS => "Not enough buffers were supplied to send a message.",
            USERMODE_HYPERVISOR::ERROR_HV_NOT_ACKNOWLEDGED => "The previous virtual interrupt has not been acknowledged.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_VP_STATE => "A virtual processor is not in the correct state for the indicated operation.",
            USERMODE_HYPERVISOR::ERROR_HV_ACKNOWLEDGED => "The previous virtual interrupt has already been acknowledged.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_SAVE_RESTORE_STATE => "The indicated partition is not in a valid state for saving or restoring.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_SYNIC_STATE => "The hypervisor could not complete the operation because a required feature of the synthetic interrupt controller (SynIC) was disabled.",
            USERMODE_HYPERVISOR::ERROR_HV_OBJECT_IN_USE => "The hypervisor could not perform the operation because the object or value was either already in use or being used for a purpose that would not permit completing the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_PROXIMITY_DOMAIN_INFO => "The proximity domain information is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_NO_DATA => "An attempt to retrieve debugging data failed because none was available.",
            USERMODE_HYPERVISOR::ERROR_HV_INACTIVE => "The physical connection being used for debugging has not recorded any receive activity since the last operation.",
            USERMODE_HYPERVISOR::ERROR_HV_NO_RESOURCES => "There are not enough resources to complete the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_FEATURE_UNAVAILABLE => "A hypervisor feature is not available to the user.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_BUFFER => "The specified buffer was too small to contain all of the requested data.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_DEVICE_DOMAINS => "The maximum number of domains supported by the platform I/O remapping hardware is currently in use. No domains are available to assign this device to this partition.",
            USERMODE_HYPERVISOR::ERROR_HV_CPUID_FEATURE_VALIDATION => "Validation of CPUID data of the processor failed.",
            USERMODE_HYPERVISOR::ERROR_HV_CPUID_XSAVE_FEATURE_VALIDATION => "Validation of XSAVE CPUID data of the processor failed.",
            USERMODE_HYPERVISOR::ERROR_HV_PROCESSOR_STARTUP_TIMEOUT => "Processor did not respond within the timeout period.",
            USERMODE_HYPERVISOR::ERROR_HV_SMX_ENABLED => "SMX has been enabled in the BIOS.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_LP_INDEX => "The hypervisor could not perform the operation because the specified LP index is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_REGISTER_VALUE => "The supplied register value is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_VTL_STATE => "The supplied virtual trust level is not in the correct state to perform the requested operation.",
            USERMODE_HYPERVISOR::ERROR_HV_NX_NOT_DETECTED => "No execute feature (NX) is not present or not enabled in the BIOS.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_DEVICE_ID => "The supplied device ID is invalid.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_DEVICE_STATE => "The operation is not allowed in the current device state.",
            USERMODE_HYPERVISOR::ERROR_HV_PAGE_REQUEST_INVALID => "The supplied page request specifies a memory access that the guest does not have permissions to perform.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_CPU_GROUP_ID => "A CPU group with the specified CPU group Id does not exist.",
            USERMODE_HYPERVISOR::ERROR_HV_INVALID_CPU_GROUP_STATE => "The hypervisor could not perform the operation because the CPU group is entering or in an invalid state.",
            USERMODE_HYPERVISOR::ERROR_HV_OPERATION_FAILED => "The requested operation failed.",
            USERMODE_HYPERVISOR::ERROR_HV_NOT_ALLOWED_WITH_NESTED_VIRT_ACTIVE => "The hypervisor could not perform the operation because it is not allowed with nested virtualization active.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_ROOT_MEMORY => "There is not enough memory in the root partition's pool to complete the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_EVENT_BUFFER_ALREADY_FREED => "The provided event log buffer was already marked as freed.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_CONTIGUOUS_MEMORY => "There is not enough contiguous memory in the partition's pool to complete the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_DEVICE_NOT_IN_DOMAIN => "The device is not in a device domain.",
            USERMODE_HYPERVISOR::ERROR_HV_NESTED_VM_EXIT => "The requested operation would result in a nested vm-exit.",
            USERMODE_HYPERVISOR::ERROR_HV_MSR_ACCESS_FAILED => "The requested access to the model specific register failed.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_MEMORY_MIRRORING => "There is not enough memory in the hypervisor pool to complete the mirroring operation.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_CONTIGUOUS_MEMORY_MIRRORING => "There is not enough contiguous memory in the hypervisor pool to complete the mirroring operation.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_CONTIGUOUS_ROOT_MEMORY => "There is not enough contiguous memory in the root partition's pool to complete the operation.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_ROOT_MEMORY_MIRRORING => "There is not enough memory in the root partition's pool to complete the mirroring operation.",
            USERMODE_HYPERVISOR::ERROR_HV_INSUFFICIENT_CONTIGUOUS_ROOT_MEMORY_MIRRORING => "There is not enough contiguous memory in the root partition's pool to complete the mirroring operation.",
            USERMODE_HYPERVISOR::ERROR_HV_NOT_PRESENT => "No hypervisor is present on this system.",
        }
    }
}
