/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum USERMODE_HNS {
    HCN_E_NETWORK_NOT_FOUND = 0x803B0001,
    HCN_E_ENDPOINT_NOT_FOUND = 0x803B0002,
    HCN_E_LAYER_NOT_FOUND = 0x803B0003,
    HCN_E_SWITCH_NOT_FOUND = 0x803B0004,
    HCN_E_SUBNET_NOT_FOUND = 0x803B0005,
    HCN_E_ADAPTER_NOT_FOUND = 0x803B0006,
    HCN_E_PORT_NOT_FOUND = 0x803B0007,
    HCN_E_POLICY_NOT_FOUND = 0x803B0008,
    HCN_E_VFP_PORTSETTING_NOT_FOUND = 0x803B0009,
    HCN_E_INVALID_NETWORK = 0x803B000A,
    HCN_E_INVALID_NETWORK_TYPE = 0x803B000B,
    HCN_E_INVALID_ENDPOINT = 0x803B000C,
    HCN_E_INVALID_POLICY = 0x803B000D,
    HCN_E_INVALID_POLICY_TYPE = 0x803B000E,
    HCN_E_INVALID_REMOTE_ENDPOINT_OPERATION = 0x803B000F,
    HCN_E_NETWORK_ALREADY_EXISTS = 0x803B0010,
    HCN_E_LAYER_ALREADY_EXISTS = 0x803B0011,
    HCN_E_POLICY_ALREADY_EXISTS = 0x803B0012,
    HCN_E_PORT_ALREADY_EXISTS = 0x803B0013,
    HCN_E_ENDPOINT_ALREADY_ATTACHED = 0x803B0014,
    HCN_E_REQUEST_UNSUPPORTED = 0x803B0015,
    HCN_E_MAPPING_NOT_SUPPORTED = 0x803B0016,
    HCN_E_DEGRADED_OPERATION = 0x803B0017,
    HCN_E_SHARED_SWITCH_MODIFICATION = 0x803B0018,
    HCN_E_GUID_CONVERSION_FAILURE = 0x803B0019,
    HCN_E_REGKEY_FAILURE = 0x803B001A,
    HCN_E_INVALID_JSON = 0x803B001B,
    HCN_E_INVALID_JSON_REFERENCE = 0x803B001C,
    HCN_E_ENDPOINT_SHARING_DISABLED = 0x803B001D,
    HCN_E_INVALID_IP = 0x803B001E,
    HCN_E_SWITCH_EXTENSION_NOT_FOUND = 0x803B001F,
    HCN_E_MANAGER_STOPPED = 0x803B0020,
    GCN_E_MODULE_NOT_FOUND = 0x803B0021,
    GCN_E_NO_REQUEST_HANDLERS = 0x803B0022,
    GCN_E_REQUEST_UNSUPPORTED = 0x803B0023,
    GCN_E_RUNTIMEKEYS_FAILED = 0x803B0024,
    GCN_E_NETADAPTER_TIMEOUT = 0x803B0025,
    GCN_E_NETADAPTER_NOT_FOUND = 0x803B0026,
    GCN_E_NETCOMPARTMENT_NOT_FOUND = 0x803B0027,
    GCN_E_NETINTERFACE_NOT_FOUND = 0x803B0028,
    GCN_E_DEFAULTNAMESPACE_EXISTS = 0x803B0029,
    HCN_E_ICS_DISABLED = 0x803B002A,
    HCN_E_ENDPOINT_NAMESPACE_ALREADY_EXISTS = 0x803B002B,
    HCN_E_ENTITY_HAS_REFERENCES = 0x803B002C,
    HCN_E_INVALID_INTERNAL_PORT = 0x803B002D,
    HCN_E_NAMESPACE_ATTACH_FAILED = 0x803B002E,
    HCN_E_ADDR_INVALID_OR_RESERVED = 0x803B002F,
    HCN_E_INVALID_PREFIX = 0x803B0030,
    HCN_E_OBJECT_USED_AFTER_UNLOAD = 0x803B0031,
    HCN_E_INVALID_SUBNET = 0x803B0032,
    HCN_E_INVALID_IP_SUBNET = 0x803B0033,
    HCN_E_ENDPOINT_NOT_ATTACHED = 0x803B0034,
    HCN_E_ENDPOINT_NOT_LOCAL = 0x803B0035,
    HCN_INTERFACEPARAMETERS_ALREADY_APPLIED = 0x803B0036,
    HCN_E_VFP_NOT_ALLOWED = 0x803B0037,
    ERROR_HNS_PORT_ALLOCATED = 0xC03B0001,
    ERROR_HNS_MAPPING_NOT_SUPPORTED = 0xC03B0002
}

impl USERMODE_HNS {
    pub fn description(&self) -> &'static str {
        match self {
            USERMODE_HNS::HCN_E_NETWORK_NOT_FOUND => "The network was not found.",
            USERMODE_HNS::HCN_E_ENDPOINT_NOT_FOUND => "The endpoint was not found.",
            USERMODE_HNS::HCN_E_LAYER_NOT_FOUND => "The network's underlying layer was not found.",
            USERMODE_HNS::HCN_E_SWITCH_NOT_FOUND => "The virtual switch was not found.",
            USERMODE_HNS::HCN_E_SUBNET_NOT_FOUND => "The network does not have a subnet for this endpoint.",
            USERMODE_HNS::HCN_E_ADAPTER_NOT_FOUND => "An adapter was not found.",
            USERMODE_HNS::HCN_E_PORT_NOT_FOUND => "The switch-port was not found.",
            USERMODE_HNS::HCN_E_POLICY_NOT_FOUND => "An expected policy was not found.",
            USERMODE_HNS::HCN_E_VFP_PORTSETTING_NOT_FOUND => "A required VFP port setting was not found.",
            USERMODE_HNS::HCN_E_INVALID_NETWORK => "The provided network configuration is invalid or missing parameters.",
            USERMODE_HNS::HCN_E_INVALID_NETWORK_TYPE => "Invalid network type.",
            USERMODE_HNS::HCN_E_INVALID_ENDPOINT => "The provided endpoint configuration is invalid or missing parameters.",
            USERMODE_HNS::HCN_E_INVALID_POLICY => "The provided policy configuration is invalid or missing parameters.",
            USERMODE_HNS::HCN_E_INVALID_POLICY_TYPE => "Invalid policy type.",
            USERMODE_HNS::HCN_E_INVALID_REMOTE_ENDPOINT_OPERATION => "This requested operation is invalid for a remote endpoint.",
            USERMODE_HNS::HCN_E_NETWORK_ALREADY_EXISTS => "A network with this name already exists.",
            USERMODE_HNS::HCN_E_LAYER_ALREADY_EXISTS => "A network with this name already exists.",
            USERMODE_HNS::HCN_E_POLICY_ALREADY_EXISTS => "Policy information already exists on this object.",
            USERMODE_HNS::HCN_E_PORT_ALREADY_EXISTS => "The specified port already exists.",
            USERMODE_HNS::HCN_E_ENDPOINT_ALREADY_ATTACHED => "This endpoint is already attached to the switch.",
            USERMODE_HNS::HCN_E_REQUEST_UNSUPPORTED => "The specified request is unsupported.",
            USERMODE_HNS::HCN_E_MAPPING_NOT_SUPPORTED => "Port mapping is not supported on the given network.",
            USERMODE_HNS::HCN_E_DEGRADED_OPERATION => "There was an operation attempted on a degraded object.",
            USERMODE_HNS::HCN_E_SHARED_SWITCH_MODIFICATION => "Cannot modify a switch shared by multiple networks.",
            USERMODE_HNS::HCN_E_GUID_CONVERSION_FAILURE => "Failed to interpret a parameter as a GUID.",
            USERMODE_HNS::HCN_E_REGKEY_FAILURE => "Failed to process registry key.",
            USERMODE_HNS::HCN_E_INVALID_JSON => "Invalid JSON document string.",
            USERMODE_HNS::HCN_E_INVALID_JSON_REFERENCE => "The reference is invalid in the JSON document.",
            USERMODE_HNS::HCN_E_ENDPOINT_SHARING_DISABLED => "Endpoint sharing is disabled.",
            USERMODE_HNS::HCN_E_INVALID_IP => "IP address is either invalid or not part of any configured subnet(s).",
            USERMODE_HNS::HCN_E_SWITCH_EXTENSION_NOT_FOUND => "The specified switch extension does not exist on this switch.",
            USERMODE_HNS::HCN_E_MANAGER_STOPPED => "Operation cannot be performed while service is stopping.",
            USERMODE_HNS::GCN_E_MODULE_NOT_FOUND => "Operation cannot be performed while service module not found.",
            USERMODE_HNS::GCN_E_NO_REQUEST_HANDLERS => "Request Handlers not present to handle the JSON request.",
            USERMODE_HNS::GCN_E_REQUEST_UNSUPPORTED => "The specified request is unsupported.",
            USERMODE_HNS::GCN_E_RUNTIMEKEYS_FAILED => "Add runtime keys to container failed.",
            USERMODE_HNS::GCN_E_NETADAPTER_TIMEOUT => "Timeout while waiting for network adapter with the given instance id",
            USERMODE_HNS::GCN_E_NETADAPTER_NOT_FOUND => "Network adapter not found for the given instance id",
            USERMODE_HNS::GCN_E_NETCOMPARTMENT_NOT_FOUND => "Network compartment not found for the given  id",
            USERMODE_HNS::GCN_E_NETINTERFACE_NOT_FOUND => "Network interface not found for the given  id",
            USERMODE_HNS::GCN_E_DEFAULTNAMESPACE_EXISTS => "Default Namespace already exists",
            USERMODE_HNS::HCN_E_ICS_DISABLED => "Internet Connection Sharing service (SharedAccess) is disabled and cannot be started",
            USERMODE_HNS::HCN_E_ENDPOINT_NAMESPACE_ALREADY_EXISTS => "This requested operation is invalid as endpoint is already part of a network namespace.",
            USERMODE_HNS::HCN_E_ENTITY_HAS_REFERENCES => "The specified entity cannot be removed while it still has references.",
            USERMODE_HNS::HCN_E_INVALID_INTERNAL_PORT => "The internal port must exist and cannot be zero.",
            USERMODE_HNS::HCN_E_NAMESPACE_ATTACH_FAILED => "The requested operation for attach namespace failed.",
            USERMODE_HNS::HCN_E_ADDR_INVALID_OR_RESERVED => "An address provided is invalid or reserved.",
            USERMODE_HNS::HCN_E_INVALID_PREFIX => "The prefix provided is invalid.",
            USERMODE_HNS::HCN_E_OBJECT_USED_AFTER_UNLOAD => "A call was performed against an object that was torn down.",
            USERMODE_HNS::HCN_E_INVALID_SUBNET => "The provided subnet configuration is invalid or missing parameters.",
            USERMODE_HNS::HCN_E_INVALID_IP_SUBNET => "The provided IP subnet configuration is invalid or missing parameters.",
            USERMODE_HNS::HCN_E_ENDPOINT_NOT_ATTACHED => "The endpoint must be attached to complete the operation.",
            USERMODE_HNS::HCN_E_ENDPOINT_NOT_LOCAL => "The endpoint must be local to complete the operation.",
            USERMODE_HNS::HCN_INTERFACEPARAMETERS_ALREADY_APPLIED => "Cannot apply more than one InterfaceParameters policy.",
            USERMODE_HNS::HCN_E_VFP_NOT_ALLOWED => "A network of this type can not be created because VFP is not available.",
            USERMODE_HNS::ERROR_HNS_PORT_ALLOCATED => "The port is already allocated.",
            USERMODE_HNS::ERROR_HNS_MAPPING_NOT_SUPPORTED => "Port mapping is not supported on the given network.",
        }
    }
}
