/*
 * Copyright 2023 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Creative Commons Zero v1.0 Universal (CC0) License.
 * You may obtain a copy of the License at
 *
 *     http://creativecommons.org/publicdomain/zero/1.0/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the CC0 license is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pub enum WINDOWS_DEFENDER_VOLSNAP {
    ERROR_MP_UI_CONSOLIDATION_BASE = 0x80501000,
    ERROR_MP_ACTIONS_FAILED = 0x80501001,
    ERROR_MP_NOENGINE = 0x80501002,
    ERROR_MP_ACTIVE_THREATS = 0x80501003,
    ERROR_MP_NO_INTERNET_CONN = 0x80501004,
    MP_ERROR_CODE_LUA_CANCELLED = 0x80501101,
    MP_ERROR_CODE_ALREADY_SHUTDOWN = 0x80501102,
    MP_ERROR_CODE_RDEVICE_S_ASYNC_CALL_PENDING = 0x80501103,
    MP_ERROR_CODE_CANCELLED = 0x80501104,
    MP_ERROR_CODE_NO_TARGETOS = 0x80501105,
    MP_ERROR_CODE_BAD_REGEXP = 0x80501106,
    MP_ERROR_TEST_INDUCED_ERROR = 0x80501107,
    MP_ERROR_SIG_BACKUP_DISABLED = 0x80501108,
    ERR_MP_BAD_INIT_MODULES = 0x80508001,
    ERR_MP_BAD_DATABASE = 0x80508002,
    ERR_MP_BAD_UFS = 0x80508004,
    ERR_MP_NO_MEMORY = 0x80508007,
    ERR_MP_BAD_INPUT_DATA = 0x8050800C,
    ERR_MP_BAD_GLOBAL_STORAGE = 0x8050800D,
    ERR_MP_OBSOLETE = 0x8050800E,
    ERR_MP_NOT_SUPPORTED = 0x8050800F,
    ERR_MP_NO_MORE_ITEMS = 0x80508010,
    ERR_MP_DUPLICATE_SCANID = 0x80508011,
    ERR_MP_BAD_SCANID = 0x80508012,
    ERR_MP_BAD_USERDB_VERSION = 0x80508013,
    ERR_MP_RESTORE_FAILED = 0x80508014,
    ERROR_MP_FAILED_TO_SPYNET = 0x80508015,
    ERR_MP_BAD_ACTION = 0x80508016,
    ERR_MP_REMOVE_FAILED = 0x80508017,
    ERR_MP_SCAN_ABORTED = 0x80508018,
    ERR_MP_NOT_FOUND = 0x80508019,
    ERR_MP_BAD_CONFIGURATION = 0x80508020,
    ERR_MP_QUARANTINE_FAILED = 0x80508021,
    ERR_MP_REBOOT_REQUIRED = 0x80508022,
    ERR_MP_THREAT_NOT_FOUND = 0x80508023,
    ERR_MP_FULL_SCAN_REQUIRED = 0x80508024,
    ERR_MP_MANUAL_STEPS_REQUIRED = 0x80508025,
    ERR_MP_REMOVE_NOT_SUPPORTED = 0x80508026,
    ERR_MP_REMOVE_LOW_MEDIUM_DISABLED = 0x80508027,
    ERR_MP_UNREFERENCED_8028 = 0x80508028,
    ERROR_MP_RESCAN_REQUIRED = 0x80508029,
    ERROR_MP_CALLISTO_REQUIRED = 0x80508030,
    ERROR_MP_PLATFORM_OUTDATED = 0x80508031,
    ERR_RELO_BAD_EHANDLE = 0x80509001,
    ERR_RELO_KERNEL_NOT_LOADED = 0x80509003,
    ERR_MP_BADDB_OPEN = 0x8050A001,
    ERR_MP_BADDB_HEADER = 0x8050A002,
    ERR_MP_BADDB_OLDENGINE = 0x8050A003,
    ERR_MP_BADDB_CONTENT = 0x8050A004,
    ERR_MP_BADDB_NOTSIGNED = 0x8050A005,
}

impl WINDOWS_DEFENDER_VOLSNAP {
    pub fn description(&self) -> &'static str {
        match self {
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_UI_CONSOLIDATION_BASE => "This is an internal error. The cause is not clearly defined.",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_ACTIONS_FAILED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_NOENGINE => "No engine is loaded in antimalware service to perform the requested operation.",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_ACTIVE_THREATS => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_NO_INTERNET_CONN => "Check your Internet connection, then run the scan again.",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_LUA_CANCELLED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_ALREADY_SHUTDOWN => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_RDEVICE_S_ASYNC_CALL_PENDING => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_CANCELLED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_NO_TARGETOS => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_CODE_BAD_REGEXP => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_TEST_INDUCED_ERROR => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::MP_ERROR_SIG_BACKUP_DISABLED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_INIT_MODULES => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_DATABASE => "The digital signature on the definition update file is not valid. You should try to update the definitions again.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_UFS => "The digital signature of the definition update file is not valid. You should try to update the definitions again.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_NO_MEMORY => "The antimalware engine has encountered a no memory situation.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_INPUT_DATA => "There might be a problem with your security product.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_GLOBAL_STORAGE => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_OBSOLETE => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_NOT_SUPPORTED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_NO_MORE_ITEMS => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_DUPLICATE_SCANID => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_SCANID => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_USERDB_VERSION => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_RESTORE_FAILED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_FAILED_TO_SPYNET => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_ACTION => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_REMOVE_FAILED => "It might be triggered when malware removal is not successful.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_SCAN_ABORTED => "It might have triggered when a scan fails to complete.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_NOT_FOUND => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BAD_CONFIGURATION => "There might be an engine configuration error; commonly, this is related to input data that does not allow the engine to function properly.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_QUARANTINE_FAILED => "Quarantine operation failed for a specific threat.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_REBOOT_REQUIRED => "A reboot is required to complete threat removal.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_THREAT_NOT_FOUND => "The threat might no longer be present on the media, or malware might be stopping you from scanning your device.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_FULL_SCAN_REQUIRED => "A full system scan might be required.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_MANUAL_STEPS_REQUIRED => "Manual steps are required to complete threat removal.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_REMOVE_NOT_SUPPORTED => "Remove operation for a specific threat inside the container type is not supported.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_REMOVE_LOW_MEDIUM_DISABLED => "Removal of low and medium threats might be disabled.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_UNREFERENCED_8028 => "Windows Defender has encountered an error when taking action on spyware or other potentially unwanted software.",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_RESCAN_REQUIRED => "A rescan of the threat is required.",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_CALLISTO_REQUIRED => "An offline scan is required.",
            WINDOWS_DEFENDER_VOLSNAP::ERROR_MP_PLATFORM_OUTDATED => "Windows Defender does not support the current version of the platform and requires a new version of the platform.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_RELO_BAD_EHANDLE => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_RELO_KERNEL_NOT_LOADED => "Description is missing",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BADDB_OPEN => "The scanning engine did not load because it could not load the definition database.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BADDB_HEADER => "The digital signature of the definition update file is not valid. You should try to update the definitions again.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BADDB_OLDENGINE => "Signature update request provided an older engine or signature files(s).",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BADDB_CONTENT => "The digital signature of the definition update file is not valid. You should try to update the definitions again.",
            WINDOWS_DEFENDER_VOLSNAP::ERR_MP_BADDB_NOTSIGNED => "The digital signature of the definition update file is not valid. You should try to update the definitions again.",
        }
    }
}
